// Generated Time: 03/04/2020 18:02:03
// Generated By: aikravchenko

namespace FilingPortal.Parts.CanadaTruckImport.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;

    public partial class cbdev_3030_update_rules : FpMigration
    {
        public override void Up()
        {
            AddColumn("canada_imp_truck.rule_carrier", "gross_weight_unit", c => c.String(maxLength: 3, unicode: false));
            AddColumn("canada_imp_truck.rule_carrier", "invoice_uq", c => c.String(maxLength: 3, unicode: false));
            AddColumn("canada_imp_truck.rule_importer", "country_of_origin", c => c.String(maxLength: 2, unicode: false));
            DropColumn("canada_imp_truck.rule_importer", "transport");
            DropColumn("canada_imp_truck.rule_importer", "service_option");
            DropColumn("canada_imp_truck.rule_importer", "gross_weight_unit");
            DropColumn("canada_imp_truck.rule_importer", "invoice_uq");
            DropColumn("canada_imp_truck.rule_importer", "unit_price");
            DropTable("canada_imp_truck.handbook_service_option");

            ExecuteSqlFileUp();
        }

        public override void Down()
        {
            CreateTable(
                "canada_imp_truck.handbook_service_option",
                c => new
                {
                    code = c.String(nullable: false, maxLength: 3, unicode: false),
                    description = c.String(nullable: false, maxLength: 200, unicode: false),
                })
                .PrimaryKey(t => t.code);

            AddColumn("canada_imp_truck.rule_importer", "unit_price", c => c.Decimal(precision: 18, scale: 6));
            AddColumn("canada_imp_truck.rule_importer", "invoice_uq", c => c.String(maxLength: 3, unicode: false));
            AddColumn("canada_imp_truck.rule_importer", "gross_weight_unit", c => c.String(maxLength: 3, unicode: false));
            AddColumn("canada_imp_truck.rule_importer", "service_option", c => c.String(maxLength: 3, unicode: false));
            AddColumn("canada_imp_truck.rule_importer", "transport", c => c.String(maxLength: 3, unicode: false));
            DropColumn("canada_imp_truck.rule_importer", "country_of_origin");
            DropColumn("canada_imp_truck.rule_carrier", "invoice_uq");
            DropColumn("canada_imp_truck.rule_carrier", "gross_weight_unit");

            ExecuteSqlFileDown();
        }
    }
}
