// Generated Time: 04/07/2020 13:57:42
// Generated By: AIKravchenko

namespace FilingPortal.Parts.CanadaTruckImport.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;

    public partial class cbdev_3088_update_rail_parse_script : FpMigration
    {
        public override void Up()
        {
        }

        public override void Down()
        {
        }
    }
}
