// Generated Time: 04/08/2020 18:53:12
// Generated By: AIKravchenko

namespace FilingPortal.Parts.CanadaTruckImport.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;

    public partial class cbdev_3090_add_entry_status : FpMigration
    {
        public override void Up()
        {
            AddColumn("canada_imp_truck.filing_header", "entry_status", c => c.String(maxLength: 128, unicode: false));

            ExecuteSqlFileUp();
        }

        public override void Down()
        {
            DropColumn("canada_imp_truck.filing_header", "entry_status");

            ExecuteSqlFileDown();
        }
    }
}
