// <auto-generated />
// Generated Time: 09/18/2020 17:01:29
// Generated By: AIKravchenko

namespace FilingPortal.Parts.CanadaTruckImport.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    using FilingPortal.Parts.Common.DataLayer.Base;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cbdev_3334_empty_migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cbdev_3334_empty_migration));
        
        string IMigrationMetadata.Id
        {
            get { return "202009181252518_cbdev_3334_empty_migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
