// Generated Time: 03/03/2020 12:08:23
// Generated By: IAPetrov

namespace FilingPortal.Parts.CanadaTruckImport.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;

    public partial class cbdev_3001_audit_changes : FpMigration
    {
        public override void Up()
        {
        }

        public override void Down()
        {
        }
    }
}
