// Generated Time: 05/18/2020 19:42:53
// Generated By: AIKravchenko

namespace FilingPortal.Parts.CanadaTruckImport.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;

    public partial class cbdev_3156_empty_migration : FpMigration
    {
        public override void Up()
        {
        }

        public override void Down()
        {
        }
    }
}
