// <auto-generated />
// Generated Time: 02/28/2020 12:47:57
// Generated By: aikravchenko

namespace FilingPortal.Parts.CanadaTruckImport.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    using FilingPortal.Parts.Common.DataLayer.Base;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cbdev_3015_update_resulting_tables_types_procedures : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cbdev_3015_update_resulting_tables_types_procedures));
        
        string IMigrationMetadata.Id
        {
            get { return "202002280947579_cbdev_3015_update_resulting_tables_types_procedures"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
