// <auto-generated />
// Generated Time: 03/16/2020 18:49:21
// Generated By: aikravchenko

namespace FilingPortal.Parts.CanadaTruckImport.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    using FilingPortal.Parts.Common.DataLayer.Base;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cbdev_3045_update_document_view : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cbdev_3045_update_document_view));
        
        string IMigrationMetadata.Id
        {
            get { return "202003161549212_cbdev_3045_update_document_view"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
