// Generated Time: 02/13/2020 13:49:59
// Generated By: IAPetrov

namespace FilingPortal.Parts.CanadaTruckImport.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;

    public partial class cbdev_2982_audit_remove_importer_no_from_rules : FpMigration
    {
        public override void Up()
        {
        }

        public override void Down()
        {
        }
    }
}
