// Generated Time: 02/21/2020 14:26:58
// Generated By: aikravchenko

namespace FilingPortal.Parts.CanadaTruckImport.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;

    public partial class cbdev_2988_empty_migration : FpMigration
    {
        public override void Up()
        {
        }

        public override void Down()
        {
        }
    }
}
