INSERT dbo.App_Permissions(id, description, name) VALUES (24003, 'Export Recon Records Permission', 'ExportInboundRecord')
INSERT dbo.App_Permissions(id, description, name) VALUES (24011, 'View FTA Recon Records Permission', 'ViewFtaRecord')
INSERT dbo.App_Permissions(id, description, name) VALUES (24012, 'Import FTA Recon Records Permission', 'ImportFtaRecord')
INSERT dbo.App_Permissions(id, description, name) VALUES (24013, 'Export FTA Recon Records Permission', 'ExportFtaRecord')
INSERT dbo.App_Permissions(id, description, name) VALUES (24014, 'Process FTA Recon Records Permission', 'ProcessFtaRecord')
INSERT dbo.App_Permissions(id, description, name) VALUES (24021, 'View Value Recon Records Permission', 'ViewValueRecord')
INSERT dbo.App_Permissions(id, description, name) VALUES (24022, 'Import Value Recon Records Permission', 'ImportValueRecord')
INSERT dbo.App_Permissions(id, description, name) VALUES (24023, 'Export Value Recon Records Permission', 'ExportValueRecord')
INSERT dbo.App_Permissions(id, description, name) VALUES (24024, 'Process Value Recon Records Permission', 'ProcessValueRecord')

INSERT dbo.App_Permissions_Roles(App_Permissions_FK, App_Roles_FK) VALUES (24003, 1)
INSERT dbo.App_Permissions_Roles(App_Permissions_FK, App_Roles_FK) VALUES (24011, 1)
INSERT dbo.App_Permissions_Roles(App_Permissions_FK, App_Roles_FK) VALUES (24012, 1)
INSERT dbo.App_Permissions_Roles(App_Permissions_FK, App_Roles_FK) VALUES (24013, 1)
INSERT dbo.App_Permissions_Roles(App_Permissions_FK, App_Roles_FK) VALUES (24014, 1)
INSERT dbo.App_Permissions_Roles(App_Permissions_FK, App_Roles_FK) VALUES (24021, 1)
INSERT dbo.App_Permissions_Roles(App_Permissions_FK, App_Roles_FK) VALUES (24022, 1)
INSERT dbo.App_Permissions_Roles(App_Permissions_FK, App_Roles_FK) VALUES (24023, 1)
INSERT dbo.App_Permissions_Roles(App_Permissions_FK, App_Roles_FK) VALUES (24024, 1)

INSERT dbo.App_Permissions_Roles(App_Permissions_FK, App_Roles_FK) VALUES (24003, 24000)
INSERT dbo.App_Permissions_Roles(App_Permissions_FK, App_Roles_FK) VALUES (24011, 24000)
INSERT dbo.App_Permissions_Roles(App_Permissions_FK, App_Roles_FK) VALUES (24012, 24000)
INSERT dbo.App_Permissions_Roles(App_Permissions_FK, App_Roles_FK) VALUES (24013, 24000)
INSERT dbo.App_Permissions_Roles(App_Permissions_FK, App_Roles_FK) VALUES (24014, 24000)
INSERT dbo.App_Permissions_Roles(App_Permissions_FK, App_Roles_FK) VALUES (24021, 24000)
INSERT dbo.App_Permissions_Roles(App_Permissions_FK, App_Roles_FK) VALUES (24022, 24000)
INSERT dbo.App_Permissions_Roles(App_Permissions_FK, App_Roles_FK) VALUES (24023, 24000)
INSERT dbo.App_Permissions_Roles(App_Permissions_FK, App_Roles_FK) VALUES (24024, 24000)
GO