// Generated Time: 12/20/2019 13:39:29
// Generated By: IAPetrov

namespace FilingPortal.Parts.Inbond.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;

    public partial class initial : FpMigration
    {
        public override void Up()
        {
        }

        public override void Down()
        {
        }
    }
}
