// Generated Time: 10/23/2020 16:14:04
// Generated By: iapetrov

namespace FilingPortal.Parts.Inbond.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class cbdev_3425_add_common_datalayer : FpMigration
    {
        public override void Up()
        {
        }
        
        public override void Down()
        {
        }
    }
}
