// Generated Time: 03/26/2020 14:23:37
// Generated By: aikravchenko

namespace FilingPortal.Parts.Inbond.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;

    public partial class cbdev_3068_add_app_document : FpMigration
    {
        public override void Up()
        {
        }

        public override void Down()
        {
        }
    }
}
