// Generated Time: 03/11/2020 13:06:34
// Generated By: aikravchenko

namespace FilingPortal.Parts.Inbond.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;

    public partial class cbdev_3036_update_inbond_rules : FpMigration
    {
        public override void Up()
        {
            RenameTable(name: "inbond.rule_firms_code", newName: "rule_entry");
            DropIndex("inbond.rule_entry", new[] { "firms_code_id", "carrier", "consignee_id", "manifest_qty", "transport_mode" });
            AddColumn("inbond.inbound", "port_of_destination", c => c.String(maxLength: 4, unicode: false));
            AddColumn("inbond.rule_entry", "importer_id", c => c.Guid(nullable: false));
            AddForeignKey("inbond.rule_entry", "importer_id", "dbo.Clients");
            AlterColumn("inbond.inbound", "port_of_arrival", c => c.String(maxLength: 4, unicode: false));
            AlterColumn("inbond.rule_entry", "us_port_of_destination", c => c.String(nullable: false, maxLength: 4, unicode: false));
            CreateIndex("inbond.rule_entry", new[] { "firms_code_id", "importer_id", "carrier", "consignee_id", "us_port_of_destination" }, unique: true);
            DropColumn("inbond.rule_entry", "manifest_qty");
            DropColumn("inbond.rule_entry", "transport_mode");

            ExecuteSqlFileUp();
        }

        public override void Down()
        {
            AddColumn("inbond.rule_entry", "transport_mode", c => c.String(nullable: false, maxLength: 2, unicode: false));
            AddColumn("inbond.rule_entry", "manifest_qty", c => c.Decimal(nullable: false, precision: 18, scale: 6));
            DropForeignKey("inbond.rule_entry", "importer_id", "dbo.Clients");
            DropIndex("inbond.rule_entry", new[] { "firms_code_id", "importer_id", "carrier", "consignee_id", "us_port_of_destination" });
            AlterColumn("inbond.rule_entry", "us_port_of_destination", c => c.String(maxLength: 128, unicode: false));
            AlterColumn("inbond.inbound", "port_of_arrival", c => c.String(maxLength: 128, unicode: false));
            DropColumn("inbond.rule_entry", "importer_id");
            DropColumn("inbond.inbound", "port_of_destination");
            CreateIndex("inbond.rule_entry", new[] { "firms_code_id", "carrier", "consignee_id", "manifest_qty", "transport_mode" }, unique: true);
            RenameTable(name: "inbond.rule_entry", newName: "rule_firms_code");

            ExecuteSqlFileDown();
        }
    }
}
