// <auto-generated />
// Generated Time: 06/11/2020 06:24:59
// Generated By: aikravchenko

namespace FilingPortal.Parts.Inbond.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    using FilingPortal.Parts.Common.DataLayer.Base;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cbdev_3202_empty_migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cbdev_3202_empty_migration));
        
        string IMigrationMetadata.Id
        {
            get { return "202006110324592_cbdev_3202_empty_migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
