// Generated Time: 04/20/2020 16:53:00
// Generated By: AIKravchenko

namespace FilingPortal.Parts.Inbond.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;

    public partial class cbdev_3122_remove_carrier_rule : FpMigration
    {
        public override void Up()
        {
            // Carrier rule was removed from the application without removing DB artifacts. Customer requirement.
            AddColumn("inbond.inbound", "carrier", c => c.String(maxLength: 128, unicode: false));

            ExecuteSqlFileUp();
        }

        public override void Down()
        {
            DropColumn("inbond.inbound", "carrier");

            ExecuteSqlFileDown();
        }
    }
}
