// Generated Time: 04/07/2020 14:50:53
// Generated By: AIKravchenko

namespace FilingPortal.Parts.Inbond.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;

    public partial class cbdev_3088_resolve_migration_conflicts : FpMigration
    {
        public override void Up()
        {
        }

        public override void Down()
        {
        }
    }
}
