// Generated Time: 09/22/2020 06:13:22
// Generated By: iapetrov

namespace FilingPortal.Parts.Inbond.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class cbdev_3318_add_grid_view : FpMigration
    {
        public override void Up()
        {
            AddColumn("inbond.form_section_configuration", "display_as_grid", c => c.Boolean(nullable: false));
        }
        
        public override void Down()
        {
            DropColumn("inbond.form_section_configuration", "display_as_grid");
        }
    }
}
