// <auto-generated />
// Generated Time: 05/21/2020 18:52:28
// Generated By: AIKravchenko

namespace FilingPortal.Parts.Inbond.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    using FilingPortal.Parts.Common.DataLayer.Base;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cbdev_3173_update_entry_rule : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cbdev_3173_update_entry_rule));
        
        string IMigrationMetadata.Id
        {
            get { return "202005211103444_cbdev_3173_update_entry_rule"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
