// Generated Time: 10/07/2020 01:35:31
// Generated By: AIKravchenko

namespace FilingPortal.Parts.Inbond.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;

    public partial class cbdev_3369_empty : FpMigration
    {
        public override void Up()
        {
        }

        public override void Down()
        {
        }
    }
}
