// Generated Time: 02/26/2020 17:19:19
// Generated By: aikravchenko

namespace FilingPortal.Parts.Inbond.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;

    public partial class cbdev_2995_add_inbond_carrier_handbooks : FpMigration
    {
        public override void Up()
        {
            CreateTable(
                "inbond.handbook_carrier",
                c => new
                {
                    code = c.String(nullable: false, maxLength: 12, unicode: false),
                    name = c.String(nullable: false, maxLength: 100, unicode: false),
                })
                .PrimaryKey(t => t.code);

        }

        public override void Down()
        {
            DropTable("inbond.handbook_carrier");
        }
    }
}
