// Generated Time: 02/07/2020 20:47:04
// Generated By: aikravchenko

namespace FilingPortal.Parts.Inbond.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;

    public partial class cbdev_2965_resolve_migration_conflicts : FpMigration
    {
        public override void Up()
        {
        }

        public override void Down()
        {
        }
    }
}
