// Generated Time: 01/24/2020 14:12:46
// Generated By: AIKravchenko

namespace FilingPortal.Parts.Inbond.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class cbdev_2940_add_inbond_rules : FpMigration
    {
        public override void Up()
        {
            CreateTable(
                "inbond.rule_firms_code",
                c => new
                    {
                        id = c.Int(nullable: false, identity: true),
                        firms_code_id = c.Int(nullable: false),
                        carrier = c.String(nullable: false, maxLength: 128, unicode: false),
                        consignee_id = c.Guid(nullable: false),
                        manifest_qty = c.Decimal(nullable: false, precision: 18, scale: 6),
                        transport_mode = c.String(nullable: false, maxLength: 2, unicode: false),
                        entry_type = c.String(maxLength: 128, unicode: false),
                        us_port_of_destination = c.String(maxLength: 128, unicode: false),
                        shipper_id = c.Guid(nullable: false),
                        tariff = c.String(maxLength: 128, unicode: false),
                        port_of_presentation = c.String(maxLength: 128, unicode: false),
                        foreign_destination = c.String(maxLength: 128, unicode: false),
                        created_date = c.DateTime(nullable: false),
                        created_user = c.String(maxLength: 128, unicode: false),
                    })
                .PrimaryKey(t => t.id)
                .ForeignKey("dbo.Clients", t => t.consignee_id)
                .ForeignKey("dbo.cw_firms_codes", t => t.firms_code_id)
                .ForeignKey("dbo.Clients", t => t.shipper_id)
                .Index(t => new { t.firms_code_id, t.carrier, t.consignee_id, t.manifest_qty, t.transport_mode }, unique: true)
                .Index(t => t.shipper_id);
            
            CreateTable(
                "inbond.rule_transport_mode",
                c => new
                    {
                        id = c.Int(nullable: false, identity: true),
                        carrier = c.String(nullable: false, maxLength: 128, unicode: false),
                        transport_mode = c.String(nullable: false, maxLength: 2, unicode: false),
                        created_date = c.DateTime(nullable: false),
                        created_user = c.String(maxLength: 128, unicode: false),
                    })
                .PrimaryKey(t => t.id)
                .Index(t => t.carrier, unique: true);
            
            CreateTable(
                "inbond.rule_carrier",
                c => new
                    {
                        id = c.Int(nullable: false, identity: true),
                        importer_id = c.Guid(nullable: false),
                        firms_code_id = c.Int(nullable: false),
                        consignee_id = c.Guid(nullable: false),
                        carrier = c.String(nullable: false, maxLength: 128, unicode: false),
                        created_date = c.DateTime(nullable: false),
                        created_user = c.String(maxLength: 128, unicode: false),
                    })
                .PrimaryKey(t => t.id)
                .ForeignKey("dbo.Clients", t => t.consignee_id)
                .ForeignKey("dbo.cw_firms_codes", t => t.firms_code_id)
                .ForeignKey("dbo.Clients", t => t.importer_id)
                .Index(t => new { t.importer_id, t.firms_code_id, t.consignee_id }, unique: true);

            ExecuteSqlFileUp();
            
        }
        
        public override void Down()
        {
            DropForeignKey("inbond.rule_carrier", "importer_id", "dbo.Clients");
            DropForeignKey("inbond.rule_carrier", "firms_code_id", "dbo.cw_firms_codes");
            DropForeignKey("inbond.rule_carrier", "consignee_id", "dbo.Clients");
            DropForeignKey("inbond.rule_firms_code", "shipper_id", "dbo.Clients");
            DropForeignKey("inbond.rule_firms_code", "firms_code_id", "dbo.cw_firms_codes");
            DropForeignKey("inbond.rule_firms_code", "consignee_id", "dbo.Clients");
            DropIndex("inbond.rule_carrier", new[] { "importer_id", "firms_code_id", "consignee_id" });
            DropIndex("inbond.rule_transport_mode", new[] { "carrier" });
            DropIndex("inbond.rule_firms_code", new[] { "shipper_id" });
            DropIndex("inbond.rule_firms_code", new[] { "firms_code_id", "carrier", "consignee_id", "manifest_qty", "transport_mode" });
            DropTable("inbond.rule_carrier");
            DropTable("inbond.rule_transport_mode");
            DropTable("inbond.rule_firms_code");

            ExecuteSqlFileDown();
        }
    }
}
