// Generated Time: 04/29/2020 19:51:41
// Generated By: AIKravchenko

namespace FilingPortal.Parts.Inbond.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;

    public partial class cbdev_3134_update_field_configuration : FpMigration
    {
        public override void Up()
        {
            AddColumn("inbond.form_configuration", "overridden_type", c => c.String(maxLength: 128, unicode: false));

            ExecuteSqlFileUp();
        }

        public override void Down()
        {
            DropColumn("inbond.form_configuration", "overridden_type");

            ExecuteSqlFileDown();
        }
    }
}
