// Generated Time: 02/26/2020 12:20:15
// Generated By: aikravchenko

namespace FilingPortal.Parts.Inbond.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;

    public partial class cbdev_2995_update_transport_mode_rule : FpMigration
    {
        public override void Up()
        {
            DropIndex("inbond.rule_transport_mode", new[] { "carrier" });
            AddColumn("inbond.rule_transport_mode", "importer_id", c => c.Guid(nullable: true));
            AddColumn("inbond.rule_transport_mode", "firms_code_id", c => c.Int(nullable: true));
            AddColumn("inbond.rule_transport_mode", "consignee_id", c => c.Guid(nullable: true));
            AddForeignKey("inbond.rule_transport_mode", "importer_id", "dbo.Clients");
            AddForeignKey("inbond.rule_transport_mode", "firms_code_id", "dbo.cw_firms_codes");
            AddForeignKey("inbond.rule_transport_mode", "consignee_id", "dbo.Clients");

            ExecuteSqlFileUp();

            CreateIndex("inbond.rule_transport_mode", new[] { "importer_id", "firms_code_id", "consignee_id", "carrier" }, unique: true);
        }

        public override void Down()
        {
            DropForeignKey("inbond.rule_transport_mode", "importer_id", "dbo.Clients");
            DropForeignKey("inbond.rule_transport_mode", "firms_code_id", "dbo.cw_firms_codes");
            DropForeignKey("inbond.rule_transport_mode", "consignee_id", "dbo.Clients");
            DropIndex("inbond.rule_transport_mode", new[] { "importer_id", "firms_code_id", "consignee_id", "carrier" });
            DropColumn("inbond.rule_transport_mode", "consignee_id");
            DropColumn("inbond.rule_transport_mode", "firms_code_id");
            DropColumn("inbond.rule_transport_mode", "importer_id");
            CreateIndex("inbond.rule_transport_mode", "carrier", unique: true);

            ExecuteSqlFileDown();
        }
    }
}
