// <auto-generated />
// Generated Time: 02/07/2020 12:34:40
// Generated By: aikravchenko

namespace FilingPortal.Parts.Inbond.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    using FilingPortal.Parts.Common.DataLayer.Base;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cbdev_2965_add_marks_remarks_templates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cbdev_2965_add_marks_remarks_templates));
        
        string IMigrationMetadata.Id
        {
            get { return "202002070901377_cbdev_2965_add_marks_remarks_templates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
