// Generated Time: 02/03/2020 15:26:00
// Generated By: IAPetrov

namespace FilingPortal.Parts.Inbond.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class cbdev_2966_audit_changes : FpMigration
    {
        public override void Up()
        {
        }
        
        public override void Down()
        {
        }
    }
}
