// Generated Time: 03/27/2020 22:11:40
// Generated By: aikravchenko

namespace FilingPortal.Parts.Inbond.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;

    public partial class cbdev_3048_resolve_migration_conflicts : FpMigration
    {
        public override void Up()
        {
        }

        public override void Down()
        {
        }
    }
}
