ALTER VIEW dbo.Truck_Report 
AS SELECT
  tfd.FILING_HEADERS_FK
 ,tfd.TI_FK
 ,tfd.Supplier
 ,tfd.Importer
 ,tfd.Shipment_Type
 ,tfd.Transport
 ,tfd.Entry_Type
 ,tfd.RLF
 ,tfd.Enable_Entry_Sum
 ,tfd.Type
 ,tfd.Certify_Cargo_Release
 ,tfd.Service
 ,tfd.Issuer
 ,tfd.Master_Bill
 ,tfd.SCAC
 ,tfd.Discharge
 ,tfd.Entry_Port
 ,tfd.Dep
 ,tfd.Arr
 ,tfd.Arr_2
 ,tfd.HMF
 ,tfd.Origin
 ,tfd.Destination
 ,tfd.State
 ,tfd.Country_of_Export
 ,tfd.ETA
 ,tfd.Date
 ,tfd.Description
 ,tfd.Owner_Ref
 ,tfd.INCO
 ,tfd.Total_Weight
 ,tfd.Total_Volume
 ,tfd.No_Packages
 ,tfd.Code
 ,tfd.Centralized_Exam_Site
 ,tfd.Purchased
 ,tfd.Manual_Entry
 ,tfd.Importer_of_record
 ,tfd.Split_Shipment_Release
 ,tfd.Custom_Tab_Check_Local_Client
 ,tfd.Bill_Type
 ,tfd.Bill_Num
 ,tfd.Manifest_QTY
 ,tfd.Packing_UQ
 ,tfd.Bill_Issuer_SCAC
 ,tfd.Invoice_No
 ,tfd.Address
 ,tfd.Invoice_Total
 ,tfd.Curr
 ,tfd.Payment_Date
 ,tfd.Consignee
 ,tfd.Inv_Date
 ,tfd.Agreed_Place
 ,tfd.Inv_Gross_Weight
 ,tfd.Net_Weight
 ,tfd.Manufacturer
 ,tfd.Seller
 ,tfd.Sold_to_party
 ,tfd.Ship_to_party
 ,tfd.Broker_PGA_Contact_Name
 ,tfd.Broker_PGA_Contact_Phone
 ,tfd.Broker_PGA_Contact_Email
 ,tfd.LNO
 ,tfd.Tariff
 ,tfd.Customs_QTY
 ,tfd.Line_Price
 ,tfd.Goods_Description
 ,tfd.ORG
 ,tfd.SPI
 ,tfd.Gr_Weight
 ,tfd.UQ
 ,tfd.Price_Unit
 ,tfd.Prod_ID_1
 ,tfd.Attribute_1
 ,tfd.Attribute_2_manual
 ,tfd.Attribute_3
 ,tfd.Export
 ,tfd.Invoice_Qty
 ,tfd.Invoice_Qty_Unit
 ,tfd.Inv_Price
 ,tfd.Gross_Weight
 ,tfd.FIRMs_Code
 ,tfd.Amount
 ,tfd.CIF_Component
 ,tfd.EPA_TSCA_Toxic_Substance_Control_Act_Indicator
 ,tfd.TSCA_Indicator
 ,tfd.Certifying_Individual
 ,tfd.Branch
 ,tfd.Broker
 ,tfd.Merge_By
 ,tfd.Tax_Deferrable_Ind
 ,tfd.Preparer_Dist_Port
 ,tfd.Recon_Issue
 ,tfd.FTA_Recon
 ,tfd.Bond_Type
 ,tfd.Payment_Type
 ,tfd.Broker_to_Pay
 ,tfd.Prelim_Statement_Date
 ,tfd.Submitter
 ,tfd.MID
 ,tfd.Manufacturer_Code
 ,tfd.Surety_Code
FROM dbo.Truck_Filing_Headers tfh
LEFT OUTER JOIN dbo.Truck_FilingData tfd
  ON tfd.FILING_HEADERS_FK = tfh.id
WHERE tfh.MappingStatus = 2
GO
