SET IDENTITY_INSERT dbo.Vessel_Import_Sections ON
INSERT INTO dbo.Vessel_Import_Sections (id, [name], title, table_name, [procedure_name], is_array, parent_id) VALUES
  (1, 'root', 'Root', NULL, NULL, CONVERT(bit, 'False'), NULL)
  ,(2, 'declaration', 'Declaration', 'Vessel_Import_Declarations', 'vessel_import_add_declaration_record', CONVERT(bit, 'False'), 1)
  ,(3, 'invoice', 'Invoices', NULL, NULL, CONVERT(bit, 'False'), 1)
  ,(4, 'invoice_header', 'Invoice', 'Vessel_Import_Invoice_Headers', 'vessel_import_add_invoice_header_record', CONVERT(bit, 'True'), 3)
  ,(5, 'invoice_line', 'Line', 'Vessel_Import_Invoice_Lines', 'vessel_import_add_invoice_line_record', CONVERT(bit, 'True'), 4)
  ,(6, 'packing', 'Packing', 'Vessel_Import_Packings', 'vessel_import_add_packing_record', CONVERT(bit, 'False'), 1)
  ,(7, 'misc', 'MISC', 'Vessel_Import_Miscs', 'vessel_import_add_misc_record', CONVERT(bit, 'False'), 1)
SET IDENTITY_INSERT dbo.Vessel_Import_Sections OFF
GO

INSERT dbo.Vessel_Import_Def_Values
	(section_id, editable, has_default_value, mandatory, column_name, created_date, created_user, default_value, display_on_ui, [manual], single_filing_order, [description], label, paired_field_table, paired_field_column, handbook_name) VALUES 
	(2, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'main_supplier', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Main Supplier', NULL, NULL, NULL)
	,(2, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'importer', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Importer', NULL, NULL, NULL)
	,(2, CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), 'shpt_type', GETDATE(), SUSER_NAME(), 'Imp', 1, 0, NULL, NULL, 'Shipment type', NULL, NULL, NULL)
	,(2, CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), 'transport', GETDATE(), SUSER_NAME(), 'SEA', 1, 0, NULL, NULL, 'Transport', NULL, NULL, NULL)
	,(2, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'container', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Container', NULL, NULL, NULL)
	,(2, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'ent_type', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Ent type', NULL, NULL, NULL)
	,(2, CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), 'rlf', GETDATE(), SUSER_NAME(), 'RLF', 1, 0, NULL, NULL, 'rlf', NULL, NULL, NULL)
	,(2, CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), 'message', GETDATE(), SUSER_NAME(), 'ACE', 1, 0, NULL, NULL, 'Message', NULL, NULL, NULL)
	,(2, CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), 'enable_ent_sum', GETDATE(), SUSER_NAME(), 'Y', 1, 0, NULL, NULL, 'Enable ent sum', NULL, NULL, NULL)
	,(2, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'enable_cargo_rel', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Enable cargo rel', NULL, NULL, NULL)
	,(2, CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), 'type', GETDATE(), SUSER_NAME(), 'ACE', 1, 0, NULL, NULL, 'Type', NULL, NULL, NULL)
	,(2, CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), 'certify_cargo_release', GETDATE(), SUSER_NAME(), 'Y', 1, 0, NULL, NULL, 'Certify cargo release', NULL, NULL, NULL)
	,(2, CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), 'service', GETDATE(), SUSER_NAME(), 'STD', 1, 0, NULL, NULL, 'Service', NULL, NULL, NULL)
	,(2, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'issuer', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Issuer', NULL, NULL, NULL)
	,(2, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'ocean_bill', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Ocean Bill', NULL, NULL, NULL)
	,(2, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'vessel', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Vessel', NULL, NULL, NULL)
	,(2, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'voyage', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Voyage', NULL, NULL, NULL)
	,(2, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'carrier_scac', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Carrier SCAC', NULL, NULL, NULL)
	,(2, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'port_of_discharge', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Port of discharge', NULL, NULL, NULL)
	,(2, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'port_of_loading', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Port of loading', NULL, NULL, NULL)
	,(2, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'entry_port', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Entry port', NULL, NULL, NULL)
	,(2, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'dep', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Dep.', NULL, NULL, NULL)
	,(2, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'arr', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Arr.', NULL, NULL, NULL)
	,(2, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'loading_unloco', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Loading unloco', NULL, NULL, NULL)
	,(2, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'discharage_unloco', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Discharage unloco', NULL, NULL, NULL)
	,(2, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'hmf', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'hmf', NULL, NULL, NULL)
	,(2, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'origin', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Origin', NULL, NULL, NULL)
	,(2, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'destination', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Destination', NULL, NULL, NULL)
	,(2, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'etd', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'ETD', NULL, NULL, NULL)
	,(2, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'eta', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'ETA', NULL, NULL, NULL)
	,(2, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'dest_state', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Dest state', NULL, NULL, NULL)
	,(2, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'country_of_export', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Country of export', NULL, NULL, NULL)
	,(2, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'export_date', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Export date', NULL, NULL, NULL)
	,(2, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'description', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Description', NULL, NULL, NULL)
	,(2, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'owner_ref', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Owner ref', NULL, NULL, NULL)
	,(2, CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), 'inco', GETDATE(), SUSER_NAME(), 'FOB', 1, 0, NULL, NULL, 'INCO', NULL, NULL, NULL)
	,(2, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'firms_code', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Firms code', NULL, NULL, NULL)
	,(2, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'entry_number', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Entry number', NULL, NULL, NULL)
	,(2, CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), 'purchased', GETDATE(), SUSER_NAME(), 'Y', 1, 0, NULL, NULL, 'Purchased', NULL, NULL, NULL)
	,(2, CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), 'check_local_client', GETDATE(), SUSER_NAME(), 'OK', 1, 0, NULL, NULL, 'Check local client', NULL, NULL, NULL)
	
	,(4, CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), 'invoice_number', GETDATE(), SUSER_NAME(), '1', 1, 0, NULL, NULL, 'Invoice number', NULL, NULL, NULL)
	,(4, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'supplier', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Supplier', NULL, NULL, NULL)
	,(4, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'supplier_address', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Supplier address', NULL, NULL, NULL)
	,(4, CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), 'inco', GETDATE(), SUSER_NAME(), 'FOB', 1, 0, NULL, NULL, 'INCO', NULL, NULL, NULL)
	,(4, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'invoice_total', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Invoice total', NULL, NULL, NULL)
	,(4, CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), 'invoice_total_currency', GETDATE(), SUSER_NAME(), 'USD', 1, 0, NULL, NULL, 'Invoice total currency', NULL, NULL, NULL)
	,(4, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'line_total', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Line total', NULL, NULL, NULL)
	,(4, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'country_of_origin', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Country of origin', NULL, NULL, NULL)
	,(4, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'country_of_export', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'country of export', NULL, NULL, NULL)
	,(4, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'consignee', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Consignee', NULL, NULL, NULL)
	,(4, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'consignee_address', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Consignee address', NULL, NULL, NULL)
	,(4, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'export_date', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Export date', NULL, NULL, NULL)
	,(4, CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), 'transaction_related', GETDATE(), SUSER_NAME(), 'N', 1, 0, NULL, NULL, 'Transaction related', NULL, NULL, NULL)
	,(4, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'seller', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Seller', NULL, NULL, NULL)
	,(4, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'sold_to_party', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Sold to party', NULL, NULL, NULL)
	,(4, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'ship_to_party', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Ship to party', NULL, NULL, NULL)
	,(4, CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), 'broker_pga_contact_name', GETDATE(), SUSER_NAME(), 'Alessandra Mediago', 1, 0, NULL, NULL, 'Broker pga contact name', NULL, NULL, NULL)
	,(4, CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), 'broker_pga_contact_phone', GETDATE(), SUSER_NAME(), '212-363-9300', 1, 0, NULL, NULL, 'Broker pga contact phone', NULL, NULL, NULL)
	,(4, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'importer', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Importer', NULL, NULL, NULL)
	,(4, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'manufacturer', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Manufacturer', NULL, NULL, NULL)
	,(4, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'manufacturer_id', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Manufacturer id', NULL, NULL, NULL)
	,(4, CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), 'broker_pga_contact_email', GETDATE(), SUSER_NAME(), 'Amediago@CharterBrokerage.net', 1, 0, NULL, NULL, 'Broker pga contact email', NULL, NULL, NULL)
	
	,(5, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'entry_no', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Entry no', NULL, NULL, NULL)
	,(5, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'product', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Product', NULL, NULL, NULL)
	,(5, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'classification', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Classification', NULL, NULL, NULL)
	,(5, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'tariff', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Tariff', NULL, NULL, NULL)
	,(5, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'customs_qty', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Customs qty', NULL, NULL, NULL)
	,(5, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'customs_qty_unit', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Customs qty unit', NULL, NULL, NULL)
	,(5, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'goods_description', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Goods description', NULL, NULL, NULL)
	,(5, CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), 'spi', GETDATE(), SUSER_NAME(), 'N/A', 1, 0, NULL, NULL, 'SPI', NULL, NULL, NULL)
	,(5, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'country_of_origin', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Country of origin', NULL, NULL, NULL)
	,(5, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'country_of_export', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Country of export', NULL, NULL, NULL)
	,(5, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'destination_state', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Destination state', NULL, NULL, NULL)
	,(5, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'manufacturer', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'manufacturer', NULL, NULL, NULL)
	,(5, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'consignee', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Consignee', NULL, NULL, NULL)
	,(5, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'sold_to_party', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Sold to party', NULL, NULL, NULL)
	,(5, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'seller', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Seller', NULL, NULL, NULL)
	,(5, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'seller_address', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Seller address', NULL, NULL, NULL)
	,(5, CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), 'gross_weight', GETDATE(), SUSER_NAME(), '1', 1, 0, NULL, NULL, 'Gross weight', NULL, NULL, NULL)
	,(5, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'price', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Price', NULL, NULL, NULL)
	,(5, CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), 'prod_id', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Prod id', NULL, NULL, NULL)
	,(5, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'attribute1', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Attribute 1', NULL, NULL, NULL)
	,(5, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'attribute2', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Attribute 2', NULL, NULL, NULL)
	,(5, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'attribute3', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Attribute 3', NULL, NULL, NULL)
	,(5, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'transaction_related', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Transaction related', NULL, NULL, NULL)
	,(5, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'invoice_qty', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Invoice qty', NULL, NULL, NULL)
	,(5, CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), 'code', GETDATE(), SUSER_NAME(), 'OFT', 1, 0, NULL, NULL, 'Code', NULL, NULL, NULL)
	,(5, CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), 'amount', GETDATE(), SUSER_NAME(), '2', 1, 0, NULL, NULL, 'Amount', NULL, NULL, NULL)
	,(5, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'epa_tsca_toxic_substance_control_act_indicator', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Toxic indicator', NULL, NULL, NULL)
	,(5, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'tsca_indicator', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Tsca indicator', NULL, NULL, NULL)
	,(5, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'certifying_individual', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Certifying individual', NULL, NULL, NULL)
	,(5, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'mid', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Mid', NULL, NULL, NULL)
	,(5, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'hmf', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'hmf', NULL, NULL, NULL)
	
	,(7, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'branch', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Branch', NULL, NULL, NULL)
	,(7, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'broker', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Broker', NULL, NULL, NULL)
	,(7, CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), 'merge_by', GETDATE(), SUSER_NAME(), 'NON', 1, 0, NULL, NULL, 'Merge by', NULL, NULL, NULL)
	,(7, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'preparer_dist_port', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Preparer dist port', NULL, NULL, NULL)
	,(7, CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), 'recon_issue', GETDATE(), SUSER_NAME(), 'N/A', 1, 0, NULL, NULL, 'Recon issue', NULL, NULL, NULL)
	,(7, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'payment_type', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Payment type', NULL, NULL, NULL)
	,(7, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'fta_recon', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Fta recon', NULL, NULL, NULL)
	,(7, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'broker_to_pay', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Broker to pay', NULL, NULL, NULL)
	,(7, CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), 'inbond_type', GETDATE(), SUSER_NAME(), '8', 1, 0, NULL, NULL, 'Inbond type', NULL, NULL, NULL)
	
	,(6, CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), 'manifest_qty', GETDATE(), SUSER_NAME(), '1', 1, 0, NULL, NULL, 'Manifest qty', NULL, NULL, NULL)
	,(6, CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), 'uq', GETDATE(), SUSER_NAME(), 'VL', 1, 0, NULL, NULL, 'UQ', NULL, NULL, NULL)
	,(6, CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), 'bill_type', GETDATE(), SUSER_NAME(), 'MB', 1, 0, NULL, NULL, 'Bill type', NULL, NULL, NULL)
	,(6, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'bill_issuer_scac', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Bill issuer SCAC', NULL, NULL, NULL)
	,(6, CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), 'bill_num', GETDATE(), SUSER_NAME(), NULL, 1, 0, NULL, NULL, 'Bill num', NULL, NULL, NULL)
GO