// Generated Time: 11/17/2020 01:19:35
// Generated By: iapetrov

namespace FilingPortal.Cargowise.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;

    public partial class cbdev_3490_sync_only_us_ports : FpMigration
    {
        public override void Up()
        {
            ExecuteSqlFileUp();
        }

        public override void Down()
        {
            ExecuteSqlFileDown();
        }
    }
}
