// Generated Time: 10/30/2020 14:52:35
// Generated By: iapetrov

namespace FilingPortal.Cargowise.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;

    public partial class cbdev_3457_empty : FpMigration
    {
        public override void Up()
        {
        }

        public override void Down()
        {

        }
    }
}
