// Generated Time: 08/05/2020 15:46:46
// Generated By: iapetrov

namespace FilingPortal.Parts.Recon.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class cbdev_3276_change_cargowise_grid : FpMigration
    {
        public override void Up()
        {
            ExecuteSqlFileUp();
            
        }
        
        public override void Down()
        {
            ExecuteSqlFileDown();
        }
    }
}
