// Generated Time: 07/30/2020 16:05:24
// Generated By: aikravchenko

namespace FilingPortal.Parts.Recon.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;

    public partial class cbdev_3268_empty_migration_2 : FpMigration
    {
        public override void Up()
        {
        }

        public override void Down()
        {
        }
    }
}
