// <auto-generated />
// Generated Time: 08/10/2020 14:26:07
// Generated By: iapetrov

namespace FilingPortal.Parts.Recon.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    using FilingPortal.Parts.Common.DataLayer.Base;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cbdev_3291_change_tariff_quantity_to_decimal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cbdev_3291_change_tariff_quantity_to_decimal));
        
        string IMigrationMetadata.Id
        {
            get { return "202008101126076_cbdev_3291_change_tariff_quantity_to_decimal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
