// Generated Time: 08/10/2020 14:26:07
// Generated By: iapetrov

namespace FilingPortal.Parts.Recon.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class cbdev_3291_change_tariff_quantity_to_decimal : FpMigration
    {
        public override void Up()
        {
            AlterColumn("recon.inbound_ace_report", "line_tariff_quantity", c => c.Decimal(nullable: false, precision: 18, scale: 6));
        }
        
        public override void Down()
        {
            AlterColumn("recon.inbound_ace_report", "line_tariff_quantity", c => c.Int(nullable: false));
        }
    }
}
