// Generated Time: 11/03/2020 17:23:08
// Generated By: AIKravchenko

namespace FilingPortal.Parts.Recon.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;

    public partial class cbdev_3466_add_ace_columns : FpMigration
    {
        public override void Up()
        {
            AddColumn("recon.inbound_ace_report", "reconciliation_other_entry_summary_number", c => c.String(maxLength: 11, unicode: false));
            AddColumn("recon.inbound_ace_report", "reconciliation_fta_entry_summary_number", c => c.String(maxLength: 11, unicode: false));
            AddColumn("recon.inbound_ace_report", "line_hmf_amount", c => c.Decimal(nullable: false, precision: 18, scale: 6));
            AddColumn("recon.inbound_ace_report", "latest_psc_filed_date", c => c.DateTime());
        }

        public override void Down()
        {
            DropColumn("recon.inbound_ace_report", "latest_psc_filed_date");
            DropColumn("recon.inbound_ace_report", "line_hmf_amount");
            DropColumn("recon.inbound_ace_report", "reconciliation_fta_entry_summary_number");
            DropColumn("recon.inbound_ace_report", "reconciliation_other_entry_summary_number");
        }
    }
}
