// Generated Time: 09/22/2020 16:57:53
// Generated By: iapetrov

namespace FilingPortal.Parts.Recon.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class cbdev_3318_empty : FpMigration
    {
        public override void Up()
        {
        }
        
        public override void Down()
        {
        }
    }
}
