// Generated Time: 04/07/2020 12:45:31
// Generated By: iapetrov

namespace FilingPortal.Parts.Isf.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;

    public partial class cbdev_3086_add_containers : FpMigration
    {
        public override void Up()
        {
            CreateTable(
                "isf.inbound_containers",
                c => new
                {
                    id = c.Int(nullable: false, identity: true),
                    inbound_record_id = c.Int(nullable: false),
                    container_type = c.String(nullable: false, maxLength: 128, unicode: false),
                    container_number = c.String(nullable: false, maxLength: 128, unicode: false),
                    created_date = c.DateTime(nullable: false),
                    created_user = c.String(maxLength: 128, unicode: false),
                })
                .PrimaryKey(t => t.id)
                .ForeignKey("isf.inbound", t => t.inbound_record_id, cascadeDelete: true)
                .Index(t => t.inbound_record_id);

            Sql("EXECUTE app_create_handbook @name = 'container_types'");

            ExecuteSqlFileUp();
        }

        public override void Down()
        {
            DropForeignKey("isf.inbound_containers", "inbound_record_id", "isf.inbound");
            DropIndex("isf.inbound_containers", new[] { "inbound_record_id" });
            DropTable("isf.inbound_containers");

            Sql("DROP TABLE IF EXISTS dbo.Handbook_container_types");
        }
    }
}
