// Generated Time: 04/30/2020 14:11:30
// Generated By: iapetrov

namespace FilingPortal.Parts.Isf.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;

    public partial class cbdev_3127_add_confirmation_needed_field : FpMigration
    {
        public override void Up()
        {
            AddColumn("isf.form_configuration", "confirmation_needed", c => c.Boolean(nullable: false, defaultValue: false));

            ExecuteSqlFileUp();
        }

        public override void Down()
        {
            DropColumn("isf.form_configuration", "confirmation_needed");

            ExecuteSqlFileDown();
        }
    }
}
