// Generated Time: 10/08/2020 15:55:54
// Generated By: AIKravchenko

namespace FilingPortal.Parts.Isf.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;

    public partial class cbdev_3380_empty : FpMigration
    {
        public override void Up()
        {
        }

        public override void Down()
        {
        }
    }
}
