// Generated Time: 03/24/2020 14:14:52
// Generated By: IAPetrov

namespace FilingPortal.Parts.Isf.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class cbdev_3041_add_bills_table : FpMigration
    {
        public override void Up()
        {
            CreateTable(
                "isf.inbound_bills",
                c => new
                    {
                        id = c.Int(nullable: false, identity: true),
                        inbound_record_id = c.Int(nullable: false),
                        bill_type = c.String(nullable: false, maxLength: 2, unicode: false),
                        bill_number = c.String(nullable: false, maxLength: 14, unicode: false),
                        created_date = c.DateTime(nullable: false),
                        created_user = c.String(maxLength: 128, unicode: false),
                    })
                .PrimaryKey(t => t.id)
                .ForeignKey("isf.inbound", t => t.inbound_record_id, cascadeDelete: true)
                .Index(t => t.inbound_record_id);
            
            DropColumn("isf.inbound", "mbl");
            DropColumn("isf.inbound", "hbl");

            ExecuteSqlFileUp();
        }
        
        public override void Down()
        {
            AddColumn("isf.inbound", "hbl", c => c.String(maxLength: 128, unicode: false));
            AddColumn("isf.inbound", "mbl", c => c.String(maxLength: 128, unicode: false));
            DropForeignKey("isf.inbound_bills", "inbound_record_id", "isf.inbound");
            DropIndex("isf.inbound_bills", new[] { "inbound_record_id" });
            DropTable("isf.inbound_bills");

            ExecuteSqlFileDown();
        }
    }
}
