// Generated Time: 06/11/2020 06:26:16
// Generated By: aikravchenko

namespace FilingPortal.Parts.Isf.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;

    public partial class cbdev_3202_empty_migration : FpMigration
    {
        public override void Up()
        {
        }

        public override void Down()
        {
        }
    }
}
