// Generated Time: 12/07/2020 23:04:00
// Generated By: iapetrov

namespace FilingPortal.Parts.Isf.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;

    public partial class cbdev_3535_add_created_user_to_inbound : FpMigration
    {
        public override void Up()
        {
        }

        public override void Down()
        {
        }
    }
}
