// Generated Time: 10/26/2020 15:15:29
// Generated By: iapetrov

namespace FilingPortal.Parts.Isf.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;

    public partial class cbdev_3425_move_common_tables : FpMigration
    {
        public override void Up()
        {

        }

        public override void Down()
        {

        }
    }
}
