// <auto-generated />
// Generated Time: 04/07/2020 13:58:55
// Generated By: AIKravchenko

namespace FilingPortal.Parts.Isf.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    using FilingPortal.Parts.Common.DataLayer.Base;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cbdev_3088_update_rail_parse_script : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cbdev_3088_update_rail_parse_script));
        
        string IMigrationMetadata.Id
        {
            get { return "202004071058556_cbdev_3088_update_rail_parse_script"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
