// Generated Time: 03/30/2020 18:01:52
// Generated By: IAPetrov

namespace FilingPortal.Parts.Isf.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class cbdev_3077_extend_spi_rule_index : FpMigration
    {
        public override void Up()
        {
        }
        
        public override void Down()
        {
        }
    }
}
