// Generated Time: 04/27/2020 22:50:09
// Generated By: AIKravchenko

namespace FilingPortal.Parts.Isf.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;

    public partial class cbdev_3133_update_field_configuration : FpMigration
    {
        public override void Up()
        {
            AddColumn("isf.form_configuration", "depends_on_id", c => c.Int());

            ExecuteSqlFileUp();
        }

        public override void Down()
        {
            DropColumn("isf.form_configuration", "depends_on_id");

            ExecuteSqlFileDown();
        }
    }
}
