// Generated Time: 01/28/2021 17:33:12
// Generated By: ssugathan

namespace FilingPortal.Parts.Isf.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class csfp_20_alter_table_isf_declaration_owner_ref_col : FpMigration
    {
        public override void Up()
        {
           ExecuteSqlFileUp();
        }
        
        public override void Down()
        {
            ExecuteSqlFileDown();
        }
    }
}
