// Generated Time: 04/22/2020 13:35:59
// Generated By: iapetrov

using FilingPortal.Parts.Common.DataLayer.Base;

namespace FilingPortal.Parts.Rail.Export.DataLayer.Migrations
{
    public partial class cbdev_3120_create_carcass : FpMigration
    {
        public override void Up()
        {
            CreateTable(
                "us_exp_rail.filing_header",
                c => new
                {
                    id = c.Int(nullable: false, identity: true),
                    mapping_status = c.Byte(),
                    filing_status = c.Byte(),
                    entry_status = c.String(maxLength: 128, unicode: false),
                    created_date = c.DateTime(nullable: false),
                    created_user = c.String(nullable: false, maxLength: 128, unicode: false),
                    filing_number = c.String(maxLength: 255, unicode: false),
                    job_link = c.String(maxLength: 8000, unicode: false),
                })
                .PrimaryKey(t => t.id);

            CreateTable(
                "us_exp_rail.documents",
                c => new
                {
                    id = c.Int(nullable: false, identity: true),
                    content = c.Binary(),
                    created_date = c.DateTime(nullable: false),
                    created_user = c.String(nullable: false, maxLength: 128, unicode: false),
                    document_type = c.String(maxLength: 128, unicode: false),
                    description = c.String(maxLength: 1000, unicode: false),
                    extension = c.String(nullable: false, maxLength: 128, unicode: false),
                    file_name = c.String(nullable: false, maxLength: 255, unicode: false),
                    filing_header_id = c.Int(nullable: false),
                    inbound_record_id = c.Int(),
                })
                .PrimaryKey(t => t.id)
                .ForeignKey("us_exp_rail.filing_header", t => t.filing_header_id, cascadeDelete: true)
                .Index(t => t.filing_header_id);

            CreateTable(
                "us_exp_rail.inbound",
                c => new
                {
                    id = c.Int(nullable: false, identity: true),
                    deleted = c.Boolean(nullable: false),
                    created_date = c.DateTime(nullable: false),
                    created_user = c.String(maxLength: 128, unicode: false),
                })
                .PrimaryKey(t => t.id);

            CreateTable(
                "us_exp_rail.form_section_configuration",
                c => new
                {
                    id = c.Int(nullable: false, identity: true),
                    name = c.String(nullable: false, maxLength: 128, unicode: false),
                    title = c.String(nullable: false, maxLength: 128, unicode: false),
                    table_name = c.String(maxLength: 128, unicode: false),
                    procedure_name = c.String(maxLength: 128, unicode: false),
                    is_array = c.Boolean(nullable: false),
                    is_hidden = c.Boolean(nullable: false),
                    parent_id = c.Int(),
                })
                .PrimaryKey(t => t.id)
                .ForeignKey("us_exp_rail.form_section_configuration", t => t.parent_id)
                .Index(t => t.name, unique: true)
                .Index(t => t.parent_id);

            CreateTable(
                "us_exp_rail.form_configuration",
                c => new
                {
                    id = c.Int(nullable: false, identity: true),
                    section_id = c.Int(nullable: false),
                    has_default_value = c.Boolean(nullable: false),
                    editable = c.Boolean(nullable: false),
                    mandatory = c.Boolean(nullable: false),
                    column_name = c.String(nullable: false, maxLength: 128, unicode: false),
                    created_date = c.DateTime(nullable: false),
                    created_user = c.String(nullable: false, maxLength: 128, unicode: false),
                    value = c.String(maxLength: 512, unicode: false),
                    display_on_ui = c.Byte(nullable: false),
                    manual = c.Byte(nullable: false),
                    single_filing_order = c.Byte(),
                    description = c.String(maxLength: 128, unicode: false),
                    label = c.String(nullable: false, maxLength: 128, unicode: false),
                    paired_field_table = c.String(maxLength: 128, unicode: false),
                    paired_field_column = c.String(maxLength: 128, unicode: false),
                    handbook_name = c.String(maxLength: 128, unicode: false),
                })
                .PrimaryKey(t => t.id)
                .ForeignKey("us_exp_rail.form_section_configuration", t => t.section_id)
                .Index(t => t.section_id);

            CreateTable(
                "us_exp_rail.filing_detail",
                c => new
                {
                    filing_header_id = c.Int(nullable: false),
                    inbound_id = c.Int(nullable: false),
                })
                .PrimaryKey(t => new { t.filing_header_id, t.inbound_id })
                .ForeignKey("us_exp_rail.filing_header", t => t.filing_header_id, cascadeDelete: true)
                .ForeignKey("us_exp_rail.inbound", t => t.inbound_id, cascadeDelete: true)
                .Index(t => t.filing_header_id)
                .Index(t => t.inbound_id);

            ExecuteSqlFileUp();
        }

        public override void Down()
        {
            ExecuteSqlFileDown();

            DropForeignKey("us_exp_rail.form_section_configuration", "parent_id", "us_exp_rail.form_section_configuration");
            DropForeignKey("us_exp_rail.form_configuration", "section_id", "us_exp_rail.form_section_configuration");
            DropForeignKey("us_exp_rail.filing_detail", "inbound_id", "us_exp_rail.inbound");
            DropForeignKey("us_exp_rail.filing_detail", "filing_header_id", "us_exp_rail.filing_header");
            DropForeignKey("us_exp_rail.documents", "filing_header_id", "us_exp_rail.filing_header");
            DropIndex("us_exp_rail.filing_detail", new[] { "inbound_id" });
            DropIndex("us_exp_rail.filing_detail", new[] { "filing_header_id" });
            DropIndex("us_exp_rail.form_configuration", new[] { "section_id" });
            DropIndex("us_exp_rail.form_section_configuration", new[] { "parent_id" });
            DropIndex("us_exp_rail.form_section_configuration", new[] { "name" });
            DropIndex("us_exp_rail.documents", new[] { "filing_header_id" });
            DropTable("us_exp_rail.filing_detail");
            DropTable("us_exp_rail.form_configuration");
            DropTable("us_exp_rail.form_section_configuration");
            DropTable("us_exp_rail.inbound");
            DropTable("us_exp_rail.documents");
            DropTable("us_exp_rail.filing_header");
        }
    }
}
