// <auto-generated />
// Generated Time: 06/18/2020 14:16:18
// Generated By: aikravchenko

namespace FilingPortal.Parts.Rail.Export.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    using FilingPortal.Parts.Common.DataLayer.Base;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cbdev_3196_update_rail_export_mapping : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cbdev_3196_update_rail_export_mapping));
        
        string IMigrationMetadata.Id
        {
            get { return "202006181116185_cbdev_3196_update_rail_export_mapping"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
