// Generated Time: 06/23/2020 17:09:19
// Generated By: aikravchenko

namespace FilingPortal.Parts.Rail.Export.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;

    public partial class cbdev_3229_empty_migration : FpMigration
    {
        public override void Up()
        {
        }

        public override void Down()
        {
        }
    }
}
