//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

enum FilingStatus { 
	Open = 0, 
	InProgress = 1, 
	Filed = 2, 
	Error = 3, 
	Updated = 4
}
enum JobStatus { 
	Open = 0, 
	InReview = 1, 
	InProgress = 2, 
	Created = 3, 
	MappingError = 4, 
	CreatingError = 5, 
	WaitingUpdate = 6, 
	Updated = 7, 
	UpdatingError = 8
}
enum MappingStatus { 
	Open = 0, 
	InReview = 1, 
	InProgress = 2, 
	Mapped = 3, 
	Error = 4, 
	Updated = 5
}
