// Generated Time: 12/31/2020 13:07:36
// Generated By: iapetrov


namespace FilingPortal.Parts.Zones.Entry.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;

    public partial class cbdev_3613_remove_is_updated_from_filing_header : FpMigration
    {
        public override void Up()
        {
            DropColumn("zones_entry.filing_header", "is_updated");

            ExecuteSqlFileUp();
        }

        public override void Down()
        {
            AddColumn("zones_entry.filing_header", "is_updated", c => c.Boolean(nullable: false));
        }
    }
}
