// Generated Time: 11/17/2020 14:26:36
// Generated By: iapetrov

using Framework.DataLayer.Migrations;

namespace FilingPortal.Parts.Zones.Entry.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;

    public partial class cbdev_3364_add_missing_columns : FpMigration
    {
        public override void Up()
        {
            this.AddColumnIfNotExists("zones_entry.filing_header", "request_xml", c => c.String(unicode: false));
            this.AddColumnIfNotExists("zones_entry.filing_header", "response_xml", c => c.String(unicode: false));
            this.AddColumnIfNotExists("zones_entry.filing_header", "error_description", c => c.String(unicode: false));
            this.AddColumnIfNotExists("zones_entry.document", "Status", c => c.String(maxLength: 50, unicode: false));

            ExecuteSqlFileUp();
        }

        public override void Down()
        {
            DropColumn("zones_entry.filing_header", "request_xml");
            DropColumn("zones_entry.filing_header", "response_xml");
            DropColumn("zones_entry.filing_header", "error_description");
            DropColumn("zones_entry.document", "Status");

            ExecuteSqlFileDown();
        }
    }
}
