// Generated Time: 10/23/2020 16:13:21
// Generated By: iapetrov

namespace FilingPortal.Parts.Zones.Entry.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;

    public partial class cbdev_3425_add_common_datalayer : FpMigration
    {
        public override void Up()
        {
        }

        public override void Down()
        {
        }
    }
}
