// Generated Time: 11/13/2020 13:17:11
// Generated By: iapetrov

namespace FilingPortal.Parts.Zones.Entry.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;

    public partial class cbdev_3464_add_is_updated_to_filing_header : FpMigration
    {
        public override void Up()
        {
            AddColumn("zones_entry.filing_header", "is_updated", c => c.Boolean(nullable: false, defaultValue: false));
            CreateIndex("zones_entry.inbound", new[] { "filer_code", "entry_no" }, unique: true);

            ExecuteSqlFileUp();
        }

        public override void Down()
        {
            DropIndex("zones_entry.inbound", new[] { "filer_code", "entry_no" });
            DropColumn("zones_entry.filing_header", "is_updated");
        }
    }
}
