// Generated Time: 10/12/2020 18:40:50
// Generated By: iapetrov

namespace FilingPortal.Parts.Zones.Entry.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class cbdev_3382_add_processed_flag : FpMigration
    {
        public override void Up()
        {
        }
        
        public override void Down()
        {
        }
    }
}
