// Generated Time: 12/30/2020 17:45:56
// Generated By: iapetrov

namespace FilingPortal.Parts.Zones.Entry.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class cbdev_3617_increase_box_29_length : FpMigration
    {
        public override void Up()
        {
            AlterColumn("zones_entry.rule_importer", "f3461_box29", c => c.String(maxLength: 800, unicode: false));

            ExecuteSqlFileUp();
        }
        
        public override void Down()
        {
            AlterColumn("zones_entry.rule_importer", "f3461_box29", c => c.String(maxLength: 128, unicode: false));

            ExecuteSqlFileDown();
        }
    }
}
