// Generated Time: 11/27/2020 17:50:35
// Generated By: iapetrov

namespace FilingPortal.Parts.Zones.Entry.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class cbdev_3512_remove_colmns_from_rules : FpMigration
    {
        public override void Up()
        {
            DropColumn("zones_entry.rule_importer", "enable_cargo_release");
            DropColumn("zones_entry.rule_importer", "ftz_no");
            DropColumn("zones_entry.rule_importer", "manifest_qty");
            DropColumn("zones_entry.rule_importer", "uq");
            DropColumn("zones_entry.rule_importer", "invoice_qty_uq");
            DropColumn("zones_entry.rule_importer", "ftz_pack_qty_uq");
            DropColumn("zones_entry.rule_importer", "epa_tsca");
            DropColumn("zones_entry.rule_importer", "tsca_cert_indicator");
            DropColumn("zones_entry.rule_importer", "certifying_individual");
            DropColumn("zones_entry.rule_importer", "entry_date_election_code");

            ExecuteSqlFileUp();
        }
        
        public override void Down()
        {
            AddColumn("zones_entry.rule_importer", "entry_date_election_code", c => c.String(maxLength: 128, unicode: false));
            AddColumn("zones_entry.rule_importer", "certifying_individual", c => c.String(maxLength: 128, unicode: false));
            AddColumn("zones_entry.rule_importer", "tsca_cert_indicator", c => c.String(maxLength: 128, unicode: false));
            AddColumn("zones_entry.rule_importer", "epa_tsca", c => c.String(maxLength: 128, unicode: false));
            AddColumn("zones_entry.rule_importer", "ftz_pack_qty_uq", c => c.String(maxLength: 128, unicode: false));
            AddColumn("zones_entry.rule_importer", "invoice_qty_uq", c => c.String(maxLength: 128, unicode: false));
            AddColumn("zones_entry.rule_importer", "uq", c => c.String(maxLength: 128, unicode: false));
            AddColumn("zones_entry.rule_importer", "manifest_qty", c => c.Decimal(precision: 18, scale: 6));
            AddColumn("zones_entry.rule_importer", "ftz_no", c => c.String(maxLength: 128, unicode: false));
            AddColumn("zones_entry.rule_importer", "enable_cargo_release", c => c.Boolean(nullable: false));

            ExecuteSqlFileDown();
        }
    }
}
