// Generated Time: 12/17/2020 15:14:07
// Generated By: iapetrov

namespace FilingPortal.Parts.Zones.Entry.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;

    public partial class cbdev_3578_add_fix_for_updating_records : FpMigration
    {
        public override void Up()
        {
            AddColumn("zones_entry.inbound", "is7501", c => c.Boolean(nullable: false, defaultValue: true));

            ExecuteSqlFileUp();
        }

        public override void Down()
        {
            DropColumn("zones_entry.inbound", "is7501");

            ExecuteSqlFileDown();
        }
    }
}
