// Generated Time: 12/23/2020 15:18:30
// Generated By: iapetrov

namespace FilingPortal.Parts.Zones.Entry.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;

    public partial class cbdev_3606_add_spi_mapping : FpMigration
    {
        public override void Up()
        {
            AddColumn("zones_entry.inbound_lines", "spi", c => c.String(maxLength: 128, unicode: false));

            ExecuteSqlFileUp();
        }

        public override void Down()
        {
            DropColumn("zones_entry.inbound_lines", "spi");

            ExecuteSqlFileDown();
        }
    }
}
