// Generated Time: 02/24/2021 14:54:06
// Generated By: ssugathan

namespace FilingPortal.Parts.Zones.Entry.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class csfp_29_remove_Box29_from_rules : FpMigration
    {
        public override void Up()
        {
            DropColumn("zones_entry.rule_importer", "f3461_box29");
            ExecuteSqlFileUp();
        }
        
        public override void Down()
        {
            AddColumn("zones_entry.rule_importer", "f3461_box29", c => c.String(maxLength: 800, unicode: false));
            ExecuteSqlFileDown();
        }
    }
}
