// <auto-generated />
// Generated Time: 02/04/2021 17:03:30
// Generated By: ssugathan

namespace FilingPortal.Parts.Zones.Entry.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    using FilingPortal.Parts.Common.DataLayer.Base;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cbdev_18_changed_SPI_mapping : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cbdev_18_changed_SPI_mapping));
        
        string IMigrationMetadata.Id
        {
            get { return "202102042203304_cbdev_18_changed_SPI_mapping"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
