// <auto-generated />
// Generated Time: 02/11/2021 10:38:13
// Generated By: ssugathan

namespace FilingPortal.Parts.Zones.Entry.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    using FilingPortal.Parts.Common.DataLayer.Base;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class csfp_26_add_ftz_date_to_report_column : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(csfp_26_add_ftz_date_to_report_column));
        
        string IMigrationMetadata.Id
        {
            get { return "202102111538131_csfp_26_add_ftz_date_to_report_column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
