// <auto-generated />
// Generated Time: 02/04/2021 18:41:04
// Generated By: ssugathan

namespace FilingPortal.Parts.Zones.Entry.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    using FilingPortal.Parts.Common.DataLayer.Base;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CSFP_24_add_programcode_to_inbound_line : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CSFP_24_add_programcode_to_inbound_line));
        
        string IMigrationMetadata.Id
        {
            get { return "202102042337460_CSFP_24_add_programcode_to_inbound_line"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
