//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum CanadaImpTruckPermissions { 
	ViewInboundRecord = 20001, 
	DeleteInboundRecord = 20002, 
	FileInboundRecord = 20003, 
	ImportInboundRecord = 20004, 
	ViewRules = 20005, 
	EditRules = 20006, 
	DeleteRules = 20007
}
export class CanadaImpTruckGridNames
{
	public static InboundRecords: string = `canada_imp_truck_inbound`;
	public static RuleVendor: string = `canada_imp_truck_rule_vendor`;
	public static RulePortRecords: string = `canada_imp_truck_rule_port`;
	public static RuleProduct: string = `canada_imp_truck_rule_product`;
	public static DefaultValues: string = `canada_imp_truck_default_values`;
	public static FilingGrid: string = `canada_imp_truck_filing_grid`;
}
export abstract class CanadaImpTruckDataProviderNames
{
	public static TableColumns: string = `canada_imp_truck_TableColumns`;
	public static TableNames: string = `canada_imp_truck_TableNames`;
	public static Carriers: string = `canada_imp_truck_Carriers`;
	public static ProductCodes: string = `canada_imp_truck_ProductCodes`;
	public static FormConfiguration: string = `canada_imp_truck_FormConfiguration`;
}
export class CanadaImpTruckPageConfigNames
{
	public static InboundActions: string = `canada_imp_truck_InboundActionsConfiguration`;
	public static InboundListActions: string = `canada_imp_truck_InboundListActionsConfiguration`;
	public static InboundViewPageActions: string = `canada_imp_truck_InboundViewPageActionsConfiguration`;
	public static RulesPageActions: string = `canada_imp_truck_RulesPageActionsConfiguration`;
	public static RulesRecordActions: string = `canada_imp_truck_RulesRecordActionsConfiguration`;
}
