//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum ReconPermissions { 
	ViewInboundRecord = 24001, 
	ImportInboundRecord = 24002, 
	ExportInboundRecord = 24003, 
	ViewFtaRecord = 24011, 
	ImportFtaRecord = 24012, 
	ExportFtaRecord = 24013, 
	ProcessFtaRecord = 24014, 
	ViewValueRecord = 24021, 
	ImportValueRecord = 24022, 
	ExportValueRecord = 24023, 
	ProcessValueRecord = 24024
}
export abstract class ReconReportNames
{
	public static CargoWiseInternal: string = `recon_cargo_wise_internal`;
	public static CargoWiseClientFta: string = `recon_cargo_wise_client_fta`;
	public static CargoWiseClientValue: string = `recon_cargo_wise_client_value`;
	public static AssociationReconEntryReport: string = `recon_entry_association`;
	public static ValueReconEntryReport: string = `recon_value_entry_report`;
	public static ValueReconEntryLineReport: string = `recon_value_entry_line_report`;
}
export abstract class ReconGridNames
{
	public static CargoWiseRecords: string = `recon_cargo_wise_records`;
	public static FtaRecords: string = `recon_fta_records`;
	public static ValueRecords: string = `recon_value_records`;
	public static AceReport: string = `recon_ace_report`;
}
export abstract class ReconDataProviderNames
{
	public static TableColumns: string = `recon_TableColumns`;
	public static TableNames: string = `recon_TableNames`;
	public static FormConfiguration: string = `recon_FormConfiguration`;
}
export class ReconPageConfigNames
{
	public static InboundActions: string = `recon_InboundActionsConfiguration`;
	public static InboundListActions: string = `recon_InboundListActionsConfiguration`;
	public static InboundViewPageActions: string = `recon_InboundViewPageActionsConfiguration`;
	public static FtaActions: string = `recon_FtaActionsConfiguration`;
	public static FtaListActions: string = `recon_FtaListActionsConfiguration`;
	public static FtaViewPageActions: string = `recon_FtaViewPageActionsConfiguration`;
	public static ValueActions: string = `recon_ValueActionsConfiguration`;
	public static ValueListActions: string = `recon_ValueListActionsConfiguration`;
	public static ValueViewPageActions: string = `recon_ValueViewPageActionsConfiguration`;
}
