// Generated Time: 04/07/2021 17:54:15
// Generated By: kkrastev

namespace FilingPortal.Parts.Zones.Ftz214.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class csfp_50_sp_add_packing_removed_join : FpMigration
    {
        public override void Up()
        {
            ExecuteSqlFileUp();
        }
        
        public override void Down()
        {
        }
    }
}
