// Generated Time: 04/20/2021 11:15:03
// Generated By: ageorg

namespace FilingPortal.Parts.Zones.Ftz214.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class csfp_55_bugfixes_declaration : FpMigration
    {
        public override void Up()
        {
            ExecuteSqlFileUp();
        }
        
        public override void Down()
        {
            ExecuteSqlFileDown();
        }
    }
}
