// Generated Time: 04/21/2021 11:09:42
// Generated By: ageorg

namespace FilingPortal.Parts.Zones.Ftz214.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class csfp_55_change_inbound_parsed_line_entity_hmf_type : FpMigration
    {
        public override void Up()
        {
            AlterColumn("zones_ftz214.inbound_parsed_line", "hmf", c => c.String(maxLength: 128, unicode: false));
        }
        
        public override void Down()
        {
            AlterColumn("zones_ftz214.inbound_parsed_line", "hmf", c => c.Decimal(precision: 18, scale: 6));
        }
    }
}
