// <auto-generated />
// Generated Time: 04/06/2021 13:36:56
// Generated By: kkrastev

namespace FilingPortal.Parts.Zones.Ftz214.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    using FilingPortal.Parts.Common.DataLayer.Base;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class csfp_34_invoice_line_number_not_editable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(invoice_line_number_not_editable));
        
        string IMigrationMetadata.Id
        {
            get { return "202104061036566_csfp_34_invoice_line_number_not_editable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
