// Generated Time: 04/01/2021 18:55:34
// Generated By: kkrastev

namespace FilingPortal.Parts.Zones.Ftz214.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class csfp_32_change_validation_length : FpMigration
    {
        public override void Up()
        {
            AlterColumn("zones_ftz214.inbound_parsed_data", "imp_carrier_name", c => c.String(maxLength: 30, unicode: false));
            AlterColumn("zones_ftz214.inbound_parsed_data", "imp_vessel", c => c.String(maxLength: 30, unicode: false));
        }
        
        public override void Down()
        {
            AlterColumn("zones_ftz214.inbound_parsed_data", "imp_vessel", c => c.String(maxLength: 23, unicode: false));
            AlterColumn("zones_ftz214.inbound_parsed_data", "imp_carrier_name", c => c.String(maxLength: 23, unicode: false));
        }
    }
}
