// <auto-generated />
// Generated Time: 02/05/2021 14:57:21
// Generated By: AIKravchenko

namespace FilingPortal.Parts.Zones.Ftz214.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    using FilingPortal.Parts.Common.DataLayer.Base;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class csfp_17_add_inbound_tables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(csfp_17_add_inbound_tables));
        
        string IMigrationMetadata.Id
        {
            get { return "202102031012500_csfp_17_add_inbound_tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
