// <auto-generated />
// Generated Time: 04/21/2021 11:09:42
// Generated By: ageorg

namespace FilingPortal.Parts.Zones.Ftz214.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    using FilingPortal.Parts.Common.DataLayer.Base;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class csfp_55_change_inbound_parsed_line_entity_hmf_type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(csfp_55_change_inbound_parsed_line_entity_hmf_type));
        
        string IMigrationMetadata.Id
        {
            get { return "202104210809425_csfp_55_change_inbound_parsed_line_entity_hmf_type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
