// <auto-generated />
// Generated Time: 04/22/2021 12:35:07
// Generated By: ageorg

namespace FilingPortal.Parts.Zones.Ftz214.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    using FilingPortal.Parts.Common.DataLayer.Base;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class csfp_67_v_inbound_grid_ftzoperatorid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(csfp_67_v_inbound_grid_ftzoperatorid));
        
        string IMigrationMetadata.Id
        {
            get { return "202104220935076_csfp_67_v_inbound_grid_ftzoperatorid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
