// <auto-generated />
// Generated Time: 04/20/2021 11:23:50
// Generated By: ageorg

namespace FilingPortal.Parts.Zones.Ftz214.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    using FilingPortal.Parts.Common.DataLayer.Base;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class csfp_55_bugfixes_packing : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(csfp_55_bugfixes_packing));
        
        string IMigrationMetadata.Id
        {
            get { return "202104200823505_csfp_55_bugfixes_packing"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
