// Generated Time: 04/22/2021 16:39:39
// Generated By: ageorg

namespace FilingPortal.Parts.Zones.Ftz214.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class csfp_55_declaration_sp_description_map : FpMigration
    {
        public override void Up()
        {
            ExecuteSqlFileUp();
        }
        
        public override void Down()
        {
            ExecuteSqlFileDown();
        }
    }
}
