// <auto-generated />
namespace FilingPortal.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CBDEV_1980_add_filer_based_information_to_truck_filing : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CBDEV_1980_add_filer_based_information_to_truck_filing));
        
        string IMigrationMetadata.Id
        {
            get { return "201812111038182_CBDEV_1980_add_filer_based_information_to_truck_filing"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
