// <auto-generated />
// Generated Time: 11/07/2019 15:13:12
// Generated By: IAPetrov

namespace FilingPortal.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cbdev_2765_create_database_structure_for_train_consist_sheet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cbdev_2765_create_database_structure_for_train_consist_sheet));
        
        string IMigrationMetadata.Id
        {
            get { return "201911071213125_cbdev_2765_create_database_structure_for_train_consist_sheet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
