// <auto-generated />
// Generated Time: 11/07/2019 12:41:51
// Generated By: aikravchenko

namespace FilingPortal.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cbdev_2778_add_pipeline_recalculate_procedure : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cbdev_2778_add_pipeline_recalculate_procedure));
        
        string IMigrationMetadata.Id
        {
            get { return "201911070941520_cbdev_2778_add_pipeline_recalculate_procedure"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
