// <auto-generated />
// Generated Time: 12/13/2019 14:37:53
// Generated By: AIKravchenko

namespace FilingPortal.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cbdev_2887_combine_units_handbook_data : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cbdev_2887_combine_units_handbook_data));
        
        string IMigrationMetadata.Id
        {
            get { return "201912131137534_cbdev_2887_combine_units_handbook_data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
