// <auto-generated />
// Generated Time: 11/11/2019 13:32:49
// Generated By: ssugathan

namespace FilingPortal.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cbdev_2808_remove_owner_ref_mapping_imp_rail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cbdev_2808_remove_owner_ref_mapping_imp_rail));
        
        string IMigrationMetadata.Id
        {
            get { return "201911111832491_cbdev_2808_remove_owner_ref_mapping_imp_rail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
