// <auto-generated />
namespace FilingPortal.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cbdev_2558_update_pipeline_invoicelines_to_fix_decimal_points_amount_gr_wt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cbdev_2558_update_pipeline_invoicelines_to_fix_decimal_points_amount_gr_wt));
        
        string IMigrationMetadata.Id
        {
            get { return "201906180318398_cbdev_2558_update_pipeline_invoicelines_to_fix_decimal_points_amount_gr_wt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
