// Generated Time: 11/28/2019 15:08:25
// Generated By: IAPetrov

using FilingPortal.Parts.Common.DataLayer.Base;

namespace FilingPortal.DataLayer.Migrations
{

    public partial class cbdev_2854_rail_audit_enhancements : FpMigration
    {
        public override void Up()
        {
            AddColumn("dbo.imp_rail_audit_daily_rules", "destination_state", c => c.String(maxLength: 2, unicode: false));
            AddColumn("dbo.imp_rail_audit_daily", "destination_state", c => c.String(maxLength: 2, unicode: false));

            ExecuteSqlFileUp();
        }

        public override void Down()
        {
            DropColumn("dbo.imp_rail_audit_daily", "destination_state");
            DropColumn("dbo.imp_rail_audit_daily_rules", "destination_state");

            ExecuteSqlFileDown();
        }
    }
}
