// Generated Time: 11/19/2019 17:11:41
// Generated By: AIKravchenko

using FilingPortal.Parts.Common.DataLayer.Base;

namespace FilingPortal.DataLayer.Migrations
{

    public partial class cbdev_2780_update_vessel_export_db_structure : FpMigration
    {
        public override void Up()
        {
            RenameTable(name: "dbo.Vessel_Export_Rule_USPPI_Consignee", newName: "exp_vessel_rule_usppi_consignee");
            RenameTable(name: "dbo.Vessel_Exports", newName: "exp_vessel_inbound");
            RenameTable(name: "dbo.Vessel_Export_Documents", newName: "exp_vessel_document");
            RenameTable(name: "dbo.Vessel_Export_Filing_Headers", newName: "exp_vessel_filing_header");
            RenameTable(name: "dbo.Vessel_Export_Def_Values", newName: "exp_vessel_form_configuration");
            RenameTable(name: "dbo.Vessel_Export_Sections", newName: "exp_vessel_form_section_configuration");
            RenameTable(name: "dbo.Vessel_Export_Filing_Details", newName: "exp_vessel_filing_detail");

            RenameColumn(table: "dbo.exp_vessel_form_configuration", name: "default_value", newName: "value");
            RenameColumn(table: "dbo.exp_vessel_document", name: "content", newName: "file_content");
            RenameColumn(table: "dbo.exp_vessel_document", name: "description", newName: "file_description");
            RenameColumn(table: "dbo.exp_vessel_document", name: "extension", newName: "file_extension");
            RenameColumn(table: "dbo.exp_vessel_filing_detail", name: "vessel_export_id", newName: "inbound_id");

            RenameIndex(table: "dbo.exp_vessel_filing_detail", name: "IX_vessel_export_id", newName: "IX_inbound_id");

            AlterColumn("dbo.imp_rail_filing_header", "created_date", c => c.DateTime(nullable: false));
            AlterColumn("dbo.imp_rail_filing_header", "created_user", c => c.String(nullable: false, maxLength: 128, unicode: false));

            DropIndex("dbo.Vessel_Export_Def_Values_Manual", "Idx_FilingHeaderId");
            DropIndex("dbo.Vessel_Export_Def_Values_Manual", "Idx_recordId_tableName_columnName");
            DropTable("dbo.Vessel_Export_Def_Values_Manual");

            ExecuteSqlFileUp();
        }

        public override void Down()
        {
            CreateTable(
                "dbo.Vessel_Export_Def_Values_Manual",
                c => new
                {
                    id = c.Int(nullable: false, identity: true),
                    editable = c.Boolean(nullable: false),
                    has_default_value = c.Boolean(nullable: false),
                    mandatory = c.Boolean(nullable: false),
                    filing_header_id = c.Int(nullable: false),
                    section_title = c.String(nullable: false, maxLength: 128, unicode: false),
                    table_name = c.String(nullable: false, maxLength: 128, unicode: false),
                    column_name = c.String(nullable: false, maxLength: 128, unicode: false),
                    modification_date = c.DateTime(nullable: false),
                    label = c.String(nullable: false, maxLength: 128, unicode: false),
                    value = c.String(maxLength: 512, unicode: false),
                    display_on_ui = c.Byte(nullable: false),
                    manual = c.Byte(nullable: false),
                    paired_field_table = c.String(maxLength: 128, unicode: false),
                    paired_field_column = c.String(maxLength: 128, unicode: false),
                    handbook_name = c.String(maxLength: 128, unicode: false),
                    parent_record_id = c.Int(nullable: false),
                    section_name = c.String(nullable: false, maxLength: 128, unicode: false),
                    record_id = c.Int(nullable: false),
                    description = c.String(maxLength: 128, unicode: false),
                })
                .PrimaryKey(t => t.id);
            CreateIndex("dbo.Vessel_Export_Def_Values_Manual", new[] { "record_id", "table_name", "column_name" }, name: "Idx_recordId_tableName_columnName");
            CreateIndex("dbo.Vessel_Export_Def_Values_Manual", "filing_header_id", name: "Idx_FilingHeaderId");

            AlterColumn("dbo.imp_rail_filing_header", "created_user", c => c.String(maxLength: 128, unicode: false));
            AlterColumn("dbo.imp_rail_filing_header", "created_date", c => c.DateTime());

            RenameIndex(table: "dbo.exp_vessel_filing_detail", name: "IX_inbound_id", newName: "IX_vessel_export_id");
            RenameColumn(table: "dbo.exp_vessel_filing_detail", name: "inbound_id", newName: "vessel_export_id");
            RenameColumn(table: "dbo.exp_vessel_document", name: "file_extension", newName: "extension");
            RenameColumn(table: "dbo.exp_vessel_document", name: "file_description", newName: "description");
            RenameColumn(table: "dbo.exp_vessel_document", name: "file_content", newName: "content");
            RenameColumn(table: "dbo.exp_vessel_form_configuration", name: "value", newName: "default_value");

            RenameTable(name: "dbo.exp_vessel_filing_detail", newName: "Vessel_Export_Filing_Details");
            RenameTable(name: "dbo.exp_vessel_form_section_configuration", newName: "Vessel_Export_Sections");
            RenameTable(name: "dbo.exp_vessel_form_configuration", newName: "Vessel_Export_Def_Values");
            RenameTable(name: "dbo.exp_vessel_filing_header", newName: "Vessel_Export_Filing_Headers");
            RenameTable(name: "dbo.exp_vessel_document", newName: "Vessel_Export_Documents");
            RenameTable(name: "dbo.exp_vessel_inbound", newName: "Vessel_Exports");
            RenameTable(name: "dbo.exp_vessel_rule_usppi_consignee", newName: "Vessel_Export_Rule_USPPI_Consignee");

            ExecuteSqlFileDown();
        }
    }
}
