// Generated Time: 11/21/2019 20:47:33
// Generated By: AIKravchenko

using FilingPortal.Parts.Common.DataLayer.Base;

namespace FilingPortal.DataLayer.Migrations
{
    public partial class cbdev_2816_resolve_migration_conflicts : FpMigration
    {
        public override void Up() { }

        public override void Down() { }
    }
}
