// Generated Time: 12/13/2019 18:19:07
// Generated By: AIKravchenko

using FilingPortal.Parts.Common.DataLayer.Base;

namespace FilingPortal.DataLayer.Migrations
{
    public partial class cbdev_2888_update_rail_filing_data_entity : FpMigration
    {
        public override void Up()
        {
        }

        public override void Down()
        {
        }
    }
}
