// Generated Time: 11/29/2019 12:10:16
// Generated By: AIKravchenko

using FilingPortal.Parts.Common.DataLayer.Base;

namespace FilingPortal.DataLayer.Migrations
{
    public partial class cbdev_2855_resolve_migration_conflicts : FpMigration
    {
        public override void Up()
        {

        }

        public override void Down()
        {

        }
    }
}
