// <auto-generated />
// Generated Time: 11/14/2019 15:55:00
// Generated By: AIKravchenko

namespace FilingPortal.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cbdev_2802_remove_scheduler_from_vessel_export_inbound : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cbdev_2802_remove_scheduler_from_vessel_export_inbound));
        
        string IMigrationMetadata.Id
        {
            get { return "201911141255007_cbdev_2802_remove_scheduler_from_vessel_export_inbound"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
