// <auto-generated />
// Generated Time: 11/11/2019 15:41:22
// Generated By: aikravchenko

namespace FilingPortal.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cdbev_2795_fix_imp_rail_issue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cdbev_2795_fix_imp_rail_issue));
        
        string IMigrationMetadata.Id
        {
            get { return "201911111241229_cdbev_2795_fix_imp_rail_issue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
