// Generated Time: 12/13/2019 17:21:33
// Generated By: AIKravchenko

using FilingPortal.Parts.Common.DataLayer.Base;

namespace FilingPortal.DataLayer.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class cbdev_2888_add_issuer_code : FpMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.handbook_issuer_code",
                c => new
                    {
                        id = c.Int(nullable: false, identity: true),
                        value = c.String(nullable: false, maxLength: 4, unicode: false),
                        display_value = c.String(maxLength: 128, unicode: false),
                        transportation_mode = c.String(maxLength: 2, unicode: false),
                    })
                .PrimaryKey(t => t.id)
                .Index(t => t.value, unique: true, name: "Idx_value");
            
        }
        
        public override void Down()
        {
            DropIndex("dbo.handbook_issuer_code", "Idx_value");
            DropTable("dbo.handbook_issuer_code");
        }
    }
}
