// <auto-generated />
// Generated Time: 11/26/2019 15:12:26
// Generated By: AIKravchenko

namespace FilingPortal.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cbdev_2846_copy_default_values_to_the_vessel_resulting_tables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cbdev_2846_copy_default_values_to_the_vessel_resulting_tables));
        
        string IMigrationMetadata.Id
        {
            get { return "201911261212268_cbdev_2846_copy_default_values_to_the_vessel_resulting_tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
