// Generated Time: 12/13/2019 14:37:53
// Generated By: AIKravchenko

using FilingPortal.Parts.Common.DataLayer.Base;

namespace FilingPortal.DataLayer.Migrations
{
    public partial class cbdev_2887_combine_units_handbook_data : FpMigration
    {
        public override void Up()
        {
            AlterColumn("dbo.imp_rail_inbound", "weight_unit", c => c.String(maxLength: 3, unicode: false));

            ExecuteSqlFileUp();
        }

        public override void Down()
        {
            AlterColumn("dbo.imp_rail_inbound", "weight_unit", c => c.String(maxLength: 2, unicode: false));
        }
    }
}
