// <auto-generated />
namespace FilingPortal.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update_truck_export_table_structure : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_truck_export_table_structure));
        
        string IMigrationMetadata.Id
        {
            get { return "201904301426477_cbdev_2474_update_truck_export_table_structure"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
