// <auto-generated />
// Generated Time: 12/04/2019 16:50:46
// Generated By: IAPetrov

namespace FilingPortal.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cbdev_2861_rail_daily_audit_add_consignee_code_to_unique_index : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cbdev_2861_rail_daily_audit_add_consignee_code_to_unique_index));
        
        string IMigrationMetadata.Id
        {
            get { return "201912041350461_cbdev_2861_rail_daily_audit_add_consignee_code_to_unique_index"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
