// Generated Time: 11/14/2019 15:55:00
// Generated By: AIKravchenko

using FilingPortal.Parts.Common.DataLayer.Base;

namespace FilingPortal.DataLayer.Migrations
{
    public partial class cbdev_2802_remove_scheduler_from_vessel_export_inbound : FpMigration
    {
        public override void Up()
        {
            DropColumn("dbo.Vessel_Exports", "scheduler");

            ExecuteSqlFileUp();
        }

        public override void Down()
        {
            AddColumn("dbo.Vessel_Exports", "scheduler", c => c.String(nullable: false, maxLength: 128, unicode: false));

            ExecuteSqlFileDown();
        }
    }
}
