// <auto-generated />
// Generated Time: 11/21/2019 15:50:00
// Generated By: AIKravchenko

namespace FilingPortal.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cbdev_2822_fix_update_entry_procedures : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cbdev_2822_fix_update_entry_procedures));
        
        string IMigrationMetadata.Id
        {
            get { return "201911211250002_cbdev_2822_fix_update_entry_procedures"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
