// <auto-generated />
// Generated Time: 11/21/2019 16:54:18
// Generated By: IAPetrov

namespace FilingPortal.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cbdev_2819_remove_trip_id_and_train_no : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cbdev_2819_remove_trip_id_and_train_no));
        
        string IMigrationMetadata.Id
        {
            get { return "201911211354182_cbdev_2819_remove_trip_id_and_train_no"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
