// Generated Time: 11/14/2019 13:51:45
// Generated By: AIKravchenko

using FilingPortal.Parts.Common.DataLayer.Base;

namespace FilingPortal.DataLayer.Migrations
{
    public partial class cbdev_2813_resolve_merge_conflicts : FpMigration
    {
        public override void Up() { }

        public override void Down() { }
    }
}
