// Generated Time: 03/30/2020 18:00:15
// Generated By: IAPetrov

using FilingPortal.Parts.Common.DataLayer.Base;

namespace FilingPortal.DataLayer.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class cbdev_3077_extend_spi_rule_index : FpMigration
    {
        public override void Up()
        {
            DropIndex("dbo.imp_rail_audit_daily_spi_rules", new[] { "importer_code", "goods_description" });
            CreateIndex("dbo.imp_rail_audit_daily_spi_rules", new[] { "importer_code", "goods_description", "date_from", "date_to" }, unique: true);
        }
        
        public override void Down()
        {
            DropIndex("dbo.imp_rail_audit_daily_spi_rules", new[] { "importer_code", "goods_description", "date_from", "date_to" });
            CreateIndex("dbo.imp_rail_audit_daily_spi_rules", new[] { "importer_code", "goods_description" }, unique: true);
        }
    }
}
