// Generated Time: 06/16/2020 13:52:05
// Generated By: iapetrov

using FilingPortal.Parts.Common.DataLayer.Base;

namespace FilingPortal.DataLayer.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class cbdev_3206_admin_add_auto_create_grid : FpMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.admin_auto_create",
                c => new
                    {
                        id = c.Int(nullable: false, identity: true),
                        shipment_type = c.String(maxLength: 128, unicode: false),
                        entry_type = c.String(maxLength: 128, unicode: false),
                        transport_mode = c.String(maxLength: 128, unicode: false),
                        importer_exporter = c.String(maxLength: 128, unicode: false),
                        auto_create = c.Boolean(nullable: false, defaultValue: false),
                        created_date = c.DateTime(nullable: false),
                        created_user = c.String(maxLength: 128, unicode: false),
                    })
                .PrimaryKey(t => t.id);
            
            ExecuteSqlFileUp();
        }
        
        public override void Down()
        {
            DropTable("dbo.admin_auto_create");
            ExecuteSqlFileDown();
        }
    }
}
