// Generated Time: 07/09/2020 14:14:19
// Generated By: iapetrov

using FilingPortal.Parts.Common.DataLayer.Base;

namespace FilingPortal.DataLayer.Migrations
{

    public partial class cbdev_3244_rail_make_freight_decimal : FpMigration
    {
        public override void Up()
        {
            AlterColumn("dbo.imp_rail_rule_importer_supplier", "freight", c => c.Decimal(precision: 18, scale: 6));

            ExecuteSqlFileUp();
        }

        public override void Down()
        {
            AlterColumn("dbo.imp_rail_rule_importer_supplier", "freight", c => c.Int());

            ExecuteSqlFileDown();
        }
    }
}
