// <auto-generated />
// Generated Time: 10/27/2020 12:56:04
// Generated By: iapetrov

namespace FilingPortal.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    using FilingPortal.Parts.Common.DataLayer.Base;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cbdev_3432_audit_show_validation_on_gross_weight_in_original_units : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cbdev_3432_audit_show_validation_on_gross_weight_in_original_units));
        
        string IMigrationMetadata.Id
        {
            get { return "202010270956045_cbdev_3432_audit_show_validation_on_gross_weight_in_original_units"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
