// Generated Time: 06/05/2020 15:14:48
// Generated By: AIKravchenko

using FilingPortal.Parts.Common.DataLayer.Base;

namespace FilingPortal.DataLayer.Migrations
{
    public partial class cbdev_3182_update_mapping_procedure : FpMigration
    {
        public override void Up()
        {
            ExecuteSqlFileUp();
        }

        public override void Down()
        {
            ExecuteSqlFileUp();
        }
    }
}
