// <auto-generated />
// Generated Time: 05/21/2020 13:55:06
// Generated By: iapetrov

namespace FilingPortal.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cbdev_3167_audit_rules_remove_unnecessary_columns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cbdev_3167_audit_rules_remove_unnecessary_columns));
        
        string IMigrationMetadata.Id
        {
            get { return "202005211055066_cbdev_3167_audit_rules_remove_unnecessary_columns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
