// Generated Time: 07/08/2020 14:15:50
// Generated By: iapetrov

using FilingPortal.Parts.Common.DataLayer.Base;

namespace FilingPortal.DataLayer.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class cbdev_3244_rail_add_port_to_importer_supplier : FpMigration
    {
        public override void Up()
        {
            AddColumn("dbo.imp_rail_rule_importer_supplier", "port", c => c.String(maxLength: 4, unicode: false));
            AddColumn("dbo.imp_rail_rule_importer_supplier", "freight_type", c => c.Int(nullable: false, defaultValue: 0));
            CreateIndex("dbo.imp_rail_rule_importer_supplier", new[] { "importer_name", "supplier_name", "product_description", "port" }, unique: true, name: "Idx__importer_supplier_description_port");

            ExecuteSqlFileUp();
        }
        
        public override void Down()
        {
            DropIndex("dbo.imp_rail_rule_importer_supplier", "Idx__importer_supplier_description_port");
            DropColumn("dbo.imp_rail_rule_importer_supplier", "freight_type");
            DropColumn("dbo.imp_rail_rule_importer_supplier", "port");

            ExecuteSqlFileDown();
        }
    }
}
