// <auto-generated />
// Generated Time: 07/08/2020 14:15:50
// Generated By: iapetrov

namespace FilingPortal.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cbdev_3244_rail_add_port_to_importer_supplier : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cbdev_3244_rail_add_port_to_importer_supplier));
        
        string IMigrationMetadata.Id
        {
            get { return "202007062318519_cbdev_3244_rail_add_port_to_importer_supplier"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
