// Generated Time: 10/14/2020 14:04:19
// Generated By: AIKravchenko

using FilingPortal.Parts.Common.DataLayer.Base;

namespace FilingPortal.DataLayer.Migrations
{

    public partial class cbdev_3385_combine_inbound_and_update_tables : FpMigration
    {
        public override void Up()
        {
            DropIndex("dbo.exp_truck_update_record", new[] { "exporter", "master_bill" });
            DropTable("dbo.exp_truck_update_record");

            AddColumn("dbo.exp_truck_inbound", "is_update", c => c.Boolean(nullable: false, defaultValue: false));
            AddColumn("dbo.exp_truck_inbound", "is_auto", c => c.Boolean(nullable: false, defaultValue: false));
            AddColumn("dbo.exp_truck_inbound", "is_auto_processed", c => c.Boolean(nullable: false, defaultValue: false));
            AddColumn("dbo.exp_truck_inbound", "validation_passed", c => c.Boolean(nullable: false, defaultValue: false));
            AddColumn("dbo.exp_truck_inbound", "validation_result", c => c.String(unicode: false));

            ExecuteSqlFileUp();
        }

        public override void Down()
        {
            CreateTable(
                "dbo.exp_truck_update_record",
                c => new
                {
                    id = c.Int(nullable: false, identity: true),
                    exporter = c.String(nullable: false, maxLength: 128, unicode: false),
                    master_bill = c.String(nullable: false, maxLength: 128, unicode: false),
                    importer = c.String(maxLength: 128, unicode: false),
                    tariff_type = c.String(maxLength: 128, unicode: false),
                    tariff = c.String(maxLength: 128, unicode: false),
                    export = c.String(maxLength: 128, unicode: false),
                    export_date = c.DateTime(),
                    customs_qty = c.Decimal(precision: 18, scale: 6),
                    price = c.Decimal(precision: 18, scale: 6),
                    gross_weight = c.Decimal(precision: 18, scale: 6),
                    gross_weight_unit = c.String(maxLength: 128, unicode: false),
                    origin = c.String(maxLength: 128, unicode: false),
                    goods_description = c.String(maxLength: 128, unicode: false),
                    routed_tran = c.String(maxLength: 128, unicode: false),
                    sold_en_route = c.String(maxLength: 128, unicode: false),
                    eccn = c.String(maxLength: 128, unicode: false),
                    hazardous = c.String(maxLength: 128, unicode: false),
                    origin_indicator = c.String(maxLength: 128, unicode: false),
                    goods_origin = c.String(maxLength: 128, unicode: false),
                    auto_refile = c.Boolean(nullable: false),
                    auto_refile_processed = c.Boolean(nullable: false),
                    created_date = c.DateTime(nullable: false),
                    created_user = c.String(nullable: false, maxLength: 128, unicode: false),
                })
                .PrimaryKey(t => t.id);
            CreateIndex("dbo.exp_truck_update_record", new[] { "exporter", "master_bill" }, unique: true);

            DropColumn("dbo.exp_truck_inbound", "validation_result");
            DropColumn("dbo.exp_truck_inbound", "validation_passed");
            DropColumn("dbo.exp_truck_inbound", "is_auto");
            DropColumn("dbo.exp_truck_inbound", "is_auto_processed");
            DropColumn("dbo.exp_truck_inbound", "is_update");

            ExecuteSqlFileDown();
        }
    }
}
