// Generated Time: 02/27/2020 11:53:55
// Generated By: aikravchenko

using FilingPortal.Parts.Common.DataLayer.Base;

namespace FilingPortal.DataLayer.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class cbdev_2995_add_common_handbooks : FpMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.handbook_entry_type",
                c => new
                    {
                        id = c.String(nullable: false, maxLength: 2, unicode: false),
                        description = c.String(maxLength: 128, unicode: false),
                    })
                .PrimaryKey(t => t.id);
            
            CreateTable(
                "dbo.handbook_transport_mode",
                c => new
                    {
                        id = c.Int(nullable: false, identity: true),
                        code_number = c.String(maxLength: 2, unicode: false),
                        code = c.String(nullable: false, maxLength: 3, unicode: false),
                        description = c.String(maxLength: 128, unicode: false),
                        country = c.String(nullable: false, maxLength: 2, unicode: false),
                    })
                .PrimaryKey(t => t.id);
            
            ExecuteSqlFileUp();
        }
        
        public override void Down()
        {
            DropTable("dbo.handbook_transport_mode");
            DropTable("dbo.handbook_entry_type");
        }
    }
}
