// Generated Time: 07/10/2020 14:40:31
// Generated By: iapetrov

using FilingPortal.Parts.Common.DataLayer.Base;

namespace FilingPortal.DataLayer.Migrations
{
    public partial class cbdev_3241_sync_domestic_ports : FpMigration
    {
        public override void Up()
        {
            DropIndex("dbo.CW_Domestic_Ports", new[] { "port_code" });
            CreateIndex("dbo.CW_Domestic_Ports", new[] { "port_code", "country" }, unique: true);
            DropColumn("dbo.CW_Domestic_Ports", "state");

            ExecuteSqlFileUp();
        }

        public override void Down()
        {
            AddColumn("dbo.CW_Domestic_Ports", "state", c => c.String(maxLength: 3, unicode: false));
            DropIndex("dbo.CW_Domestic_Ports", new[] { "port_code", "country" });
            CreateIndex("dbo.CW_Domestic_Ports", "port_code", unique: true);

            ExecuteSqlFileDown();
        }
    }
}
