// <auto-generated />
// Generated Time: 01/27/2020 17:35:51
// Generated By: IAPetrov

namespace FilingPortal.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cbdev_2959_add_canada_handbooks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cbdev_2959_add_canada_handbooks));
        
        string IMigrationMetadata.Id
        {
            get { return "202001271435515_cbdev_2959_add_canada_handbooks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
