// Generated Time: 10/27/2020 12:17:53
// Generated By: iapetrov

namespace FilingPortal.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;

    public partial class cbdev_3428_ensure_weight_conversion_functions : FpMigration
    {
        public override void Up()
        {
            ExecuteSqlFileUp();
        }

        public override void Down()
        {
        }
    }
}
