// Generated Time: 03/25/2020 16:50:28
// Generated By: IAPetrov

using FilingPortal.Parts.Common.DataLayer.Base;

namespace FilingPortal.DataLayer.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class cbdev_3067_audit_add_spi_rule : FpMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.imp_rail_audit_daily_spi_rules",
                c => new
                    {
                        id = c.Int(nullable: false, identity: true),
                        importer_code = c.String(nullable: false, maxLength: 24, unicode: false),
                        goods_description = c.String(nullable: false, maxLength: 525, unicode: false),
                        date_from = c.DateTime(nullable: false),
                        date_to = c.DateTime(nullable: false),
                        spi = c.String(nullable: false, maxLength: 3, unicode: false),
                        last_modified_by = c.String(maxLength: 50, unicode: false),
                        last_modified_date = c.DateTime(nullable: false),
                        created_date = c.DateTime(nullable: false),
                        created_user = c.String(nullable: false, maxLength: 128, unicode: false),
                    })
                .PrimaryKey(t => t.id)
                .ForeignKey("dbo.app_users", t => t.created_user, cascadeDelete: true)
                .Index(t => new { t.importer_code, t.goods_description }, unique: true)
                .Index(t => t.created_user);
            
            DropColumn("dbo.imp_rail_audit_daily_rules", "spi");
        }
        
        public override void Down()
        {
            AddColumn("dbo.imp_rail_audit_daily_rules", "spi", c => c.String(maxLength: 3, unicode: false));
            DropForeignKey("dbo.imp_rail_audit_daily_spi_rules", "created_user", "dbo.app_users");
            DropIndex("dbo.imp_rail_audit_daily_spi_rules", new[] { "created_user" });
            DropIndex("dbo.imp_rail_audit_daily_spi_rules", new[] { "importer_code", "goods_description" });
            DropTable("dbo.imp_rail_audit_daily_spi_rules");
        }
    }
}
