// Generated Time: 08/04/2020 15:52:41
// Generated By: iapetrov

using FilingPortal.Parts.Common.DataLayer.Base;

namespace FilingPortal.DataLayer.Migrations
{

    public partial class cbdev_3280_truck_export_add_autofile_filter : FpMigration
    {
        public override void Up()
        {
            AddColumn("dbo.exp_truck_filing_header", "is_auto_filed", c => c.Boolean(nullable: false, defaultValue: false));

            ExecuteSqlFileUp();
        }

        public override void Down()
        {
            DropColumn("dbo.exp_truck_filing_header", "is_auto_filed");

            ExecuteSqlFileDown();
        }
    }
}
