// Generated Time: 07/29/2020 12:37:24
// Generated By: aikravchenko

using FilingPortal.Parts.Common.DataLayer.Base;
using Framework.DataLayer.Migrations;

namespace FilingPortal.DataLayer.Migrations
{

    public partial class cbdev_3268_update_rail_rule_importer_supplier : FpMigration
    {
        public override void Up()
        {
            DropIndex("dbo.imp_rail_rule_importer_supplier", "Idx__importer_supplier_description_port");
            AddColumn("dbo.imp_rail_rule_importer_supplier", "destination", c => c.String(maxLength: 2, unicode: false));
            CreateIndex("dbo.imp_rail_rule_importer_supplier", new[] { "importer_name", "supplier_name", "product_description", "port", "destination" }, unique: true, name: "Idx__importer_supplier_description_port_destination");
            //DropColumn("dbo.imp_rail_rule_importer_supplier", "destination_state");

            ExecuteSqlFileUp();
        }

        public override void Down()
        {
            this.AddColumnIfNotExists("dbo.imp_rail_rule_importer_supplier", "destination_state", c => c.String(maxLength: 128, unicode: false));
            DropIndex("dbo.imp_rail_rule_importer_supplier", "Idx__importer_supplier_description_port_destination");
            DropColumn("dbo.imp_rail_rule_importer_supplier", "destination");
            CreateIndex("dbo.imp_rail_rule_importer_supplier", new[] { "importer_name", "supplier_name", "product_description", "port" }, unique: true, name: "Idx__importer_supplier_description_port");

            ExecuteSqlFileDown();
        }
    }
}
