// Generated Time: 06/25/2020 16:25:56
// Generated By: iapetrov

using FilingPortal.Parts.Common.DataLayer.Base;

namespace FilingPortal.DataLayer.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class cbdev_3231_truck_export_add_autofile : FpMigration
    {
        public override void Up()
        {
            AddColumn("dbo.exp_truck_update_record", "auto_refile", c => c.Boolean(nullable: false, defaultValue: false));
        }
        
        public override void Down()
        {
            DropColumn("dbo.exp_truck_update_record", "auto_refile");
        }
    }
}
