// <auto-generated />
// Generated Time: 02/11/2020 18:24:24
// Generated By: IAPetrov

namespace FilingPortal.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cbdev_2982_audit_remove_importer_no_from_rules : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cbdev_2982_audit_remove_importer_no_from_rules));
        
        string IMigrationMetadata.Id
        {
            get { return "202002111524242_cbdev_2982_audit_remove_importer_no_from_rules"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
