// <auto-generated />
// Generated Time: 07/21/2020 15:59:24
// Generated By: aikravchenko

namespace FilingPortal.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cbdev_3258_resolve_migration_conflicts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cbdev_3258_resolve_migration_conflicts));
        
        string IMigrationMetadata.Id
        {
            get { return "202007211259247_cbdev_3258_resolve_migration_conflicts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
