// <auto-generated />
// Generated Time: 03/10/2020 17:39:42
// Generated By: IAPetrov

namespace FilingPortal.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cbdev_3039_change_daily_audit_sync_join_condition : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cbdev_3039_change_daily_audit_sync_join_condition));
        
        string IMigrationMetadata.Id
        {
            get { return "202003101439424_cbdev_3039_change_daily_audit_sync_join_condition"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
