// Generated Time: 04/07/2020 14:46:18
// Generated By: AIKravchenko

using FilingPortal.Parts.Common.DataLayer.Base;

namespace FilingPortal.DataLayer.Migrations
{
    public partial class cbdev_3088_resolve_migration_conflicts : FpMigration
    {
        public override void Up()
        {
        }

        public override void Down()
        {
        }
    }
}
