// Generated Time: 10/22/2020 16:07:53
// Generated By: iapetrov

namespace FilingPortal.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;

    public partial class cbdev_3425_truck_export_change_header : FpMigration
    {
        public override void Up()
        {
            ExecuteSqlFile("202010221247108_cbdev_3425_truck_export_change_header_before.sql");

            AddColumn("dbo.exp_truck_filing_header", "job_status", c => c.Int());
            DropColumn("dbo.exp_truck_filing_header", "is_auto_filed");

            ExecuteSqlFileUp();
        }

        public override void Down()
        {
            AddColumn("dbo.exp_truck_filing_header", "is_auto_filed", c => c.Boolean(nullable: false));
            DropColumn("dbo.exp_truck_filing_header", "job_status");

            ExecuteSqlFileDown();
        }
    }
}
