// Generated Time: 11/02/2020 15:11:00
// Generated By: iapetrov

namespace FilingPortal.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;

    public partial class cbdev_3461_fix_gross_weight_validation : FpMigration
    {
        public override void Up()
        {
            ExecuteSqlFileUp();
        }

        public override void Down()
        {
            ExecuteSqlFileDown();
        }
    }
}
