// <auto-generated />
// Generated Time: 10/19/2020 15:48:53
// Generated By: iapetrov

namespace FilingPortal.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cbdev_3410_get_job_number_button_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cbdev_3410_get_job_number_button_added));
        
        string IMigrationMetadata.Id
        {
            get { return "202010191248538_cbdev_3410_get_job_number_button_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
