// Generated Time: 06/23/2020 13:42:59
// Generated By: iapetrov

using FilingPortal.Parts.Common.DataLayer.Base;

namespace FilingPortal.DataLayer.Migrations
{

    public partial class cbdev_3182_rail_revert_freight_calculation : FpMigration
    {
        public override void Up()
        {
            ExecuteSqlFile("202006051214481_cbdev_3182_update_mapping_procedure_down.sql");
        }

        public override void Down()
        {
            ExecuteSqlFile("202006051214481_cbdev_3182_update_mapping_procedure.sql");
        }
    }
}
