// Generated Time: 10/05/2020 18:37:37
// Generated By: AIKravchenko

using FilingPortal.Parts.Common.DataLayer.Base;

namespace FilingPortal.DataLayer.Migrations
{
    public partial class cbdev_3369_add_missing_columns : FpMigration
    {
        public override void Up()
        {
            // inbound table
            AddColumn("dbo.exp_truck_inbound", "modified_date", c => c.DateTime(nullable: true));
            AddColumn("dbo.exp_truck_inbound", "modified_user", c => c.String(maxLength: 128, unicode: false));
            Sql("UPDATE dbo.exp_truck_inbound SET modified_date = created_date, modified_user = created_user");
            AlterColumn("dbo.exp_truck_inbound", "modified_date",c=>c.DateTime(nullable: false));

            // update record table
            AddColumn("dbo.exp_truck_update_record", "gross_weight_unit", c => c.String(maxLength: 128, unicode: false));
            AddColumn("dbo.exp_truck_update_record", "routed_tran", c => c.String(maxLength: 128, unicode: false));
            AddColumn("dbo.exp_truck_update_record", "sold_en_route", c => c.String(maxLength: 128, unicode: false));
            AddColumn("dbo.exp_truck_update_record", "eccn", c => c.String(maxLength: 128, unicode: false));
            AddColumn("dbo.exp_truck_update_record", "hazardous", c => c.String(maxLength: 128, unicode: false));
            AddColumn("dbo.exp_truck_update_record", "origin_indicator", c => c.String(maxLength: 128, unicode: false));
            AddColumn("dbo.exp_truck_update_record", "goods_origin", c => c.String(maxLength: 128, unicode: false));
            RenameColumn("dbo.exp_truck_update_record", "load_port", "origin");

            // filing header
            AddColumn("dbo.exp_truck_filing_header", "is_updated", c => c.Boolean(nullable: false));
            AddColumn("dbo.exp_truck_filing_header", "update_status", c => c.Int(nullable: true));
            Sql("UPDATE dbo.exp_truck_filing_header SET update_status = IIF(created_date <> last_modified_date, 1, 0)");
            AlterColumn("dbo.exp_truck_filing_header", "update_status", c => c.Int(nullable: false, defaultValue: 0));
            DropColumn("dbo.exp_truck_filing_header", "last_modified_date");

            // other
            ExecuteSqlFileUp();
        }

        public override void Down()
        {
            // inbound table
            DropColumn("dbo.exp_truck_inbound", "modified_user");
            DropColumn("dbo.exp_truck_inbound", "modified_date");
            // update record table
            RenameColumn("dbo.exp_truck_update_record", "origin", "load_port");
            DropColumn("dbo.exp_truck_update_record", "goods_origin");
            DropColumn("dbo.exp_truck_update_record", "origin_indicator");
            DropColumn("dbo.exp_truck_update_record", "hazardous");
            DropColumn("dbo.exp_truck_update_record", "eccn");
            DropColumn("dbo.exp_truck_update_record", "sold_en_route");
            DropColumn("dbo.exp_truck_update_record", "routed_tran");
            DropColumn("dbo.exp_truck_update_record", "gross_weight_unit");

            // filing header
            DropColumn("dbo.exp_truck_filing_header", "is_updated");
            DropColumn("dbo.exp_truck_filing_header", "update_status");
            AddColumn("dbo.exp_truck_filing_header", "last_modified_date", c => c.DateTime(nullable: false));

            // other
            ExecuteSqlFileDown();
        }
    }
}
