// Generated Time: 05/13/2020 19:33:12
// Generated By: AIKravchenko

using FilingPortal.Parts.Common.DataLayer.Base;

namespace FilingPortal.DataLayer.Migrations
{

    public partial class cbdev_3147_update_import_truck : FpMigration
    {
        public override void Up()
        {
            DropIndex("dbo.imp_truck_inbound", "Idx__importer");
            AddColumn("dbo.imp_truck_inbound", "importer_code", c => c.String(nullable: false, maxLength: 128, unicode: false));
            AddColumn("dbo.imp_truck_inbound", "supplier_code", c => c.String(nullable: false, maxLength: 128, unicode: false));
            AlterColumn("dbo.imp_truck_inbound", "importer", c => c.String(nullable: true, maxLength: 200));
            CreateIndex("dbo.imp_truck_inbound", new[] { "importer_code", "supplier_code" }, name: "Idx__importer_supplier");

            DropIndex("dbo.imp_truck_rule_importer", "Idx__ior");
            AddColumn("dbo.imp_truck_rule_importer", "consignee_code", c => c.String(maxLength: 128, unicode: false));
            AlterColumn("dbo.imp_truck_rule_importer", "cw_ior", c => c.String(nullable: false, maxLength: 128, unicode: false));
            AlterColumn("dbo.imp_truck_rule_importer", "cw_supplier", c => c.String(nullable: false, maxLength: 128, unicode: false));
            AlterColumn("dbo.imp_truck_rule_importer", "ior", c => c.String(maxLength: 128, unicode: false));
            CreateIndex("dbo.imp_truck_rule_importer", new[] { "cw_ior", "cw_supplier" }, unique: true, name: "Idx__importer_supplier");

            ExecuteSqlFileUp();
        }

        public override void Down()
        {
            DropIndex("dbo.imp_truck_rule_importer", "Idx__importer_supplier");
            AlterColumn("dbo.imp_truck_rule_importer", "ior", c => c.String(nullable: false, maxLength: 128, unicode: false));
            AlterColumn("dbo.imp_truck_rule_importer", "cw_ior", c => c.String(maxLength: 128, unicode: false));
            AlterColumn("dbo.imp_truck_rule_importer", "cw_supplier", c => c.String(maxLength: 128, unicode: false));
            DropColumn("dbo.imp_truck_rule_importer", "consignee_code");
            CreateIndex("dbo.imp_truck_rule_importer", "ior", unique: true, name: "Idx__ior");


            DropIndex("dbo.imp_truck_inbound", "Idx__importer_supplier");
            DropColumn("dbo.imp_truck_inbound", "supplier_code");
            DropColumn("dbo.imp_truck_inbound", "importer_code");
            CreateIndex("dbo.imp_truck_inbound", "importer", name: "Idx__importer");

            ExecuteSqlFileDown();
        }
    }
}
