// Generated Time: 05/12/2020 14:50:23
// Generated By: AIKravchenko

using FilingPortal.Parts.Common.DataLayer.Base;

namespace FilingPortal.DataLayer.Migrations
{
    public partial class cbdev_3143_update_inbound_views : FpMigration
    {
        public override void Up()
        {
            DropPrimaryKey("dbo.handbook_entry_status");
            AddColumn("dbo.handbook_entry_status", "id", c => c.Int(nullable: false, identity: true));
            AddPrimaryKey("dbo.handbook_entry_status", "id");
            AlterColumn("dbo.handbook_entry_status", "status_type", c => c.String(nullable: false, maxLength: 128, unicode: false));
            CreateIndex("dbo.handbook_entry_status", new[] { "code", "status_type" }, unique: true);

            ExecuteSqlFileUp();
        }

        public override void Down()
        {
            DropIndex("dbo.handbook_entry_status", new[] { "code", "status_type" });
            DropPrimaryKey("dbo.handbook_entry_status");
            AlterColumn("dbo.handbook_entry_status", "status_type", c => c.String(maxLength: 128, unicode: false));
            DropColumn("dbo.handbook_entry_status", "id");
            AddPrimaryKey("dbo.handbook_entry_status", "code");

            ExecuteSqlFileDown();
        }
    }
}
