// Generated Time: 03/31/2020 15:38:32
// Generated By: IAPetrov

using FilingPortal.Parts.Common.DataLayer.Base;

namespace FilingPortal.DataLayer.Migrations
{

    public partial class cbdev_3080_audit_add_destination_state_to_spi_rule : FpMigration
    {
        public override void Up()
        {
            DropIndex("dbo.imp_rail_audit_daily_spi_rules", new[] { "importer_code", "goods_description", "date_from", "date_to" });
            AddColumn("dbo.imp_rail_audit_daily_spi_rules", "destination_state", c => c.String(maxLength: 2, unicode: false));
            CreateIndex("dbo.imp_rail_audit_daily_spi_rules", new[] { "importer_code", "goods_description", "destination_state", "date_from", "date_to" }, unique: true);
        }

        public override void Down()
        {
            DropIndex("dbo.imp_rail_audit_daily_spi_rules", new[] { "importer_code", "goods_description", "destination_state", "date_from", "date_to" });
            DropColumn("dbo.imp_rail_audit_daily_spi_rules", "destination_state");
            CreateIndex("dbo.imp_rail_audit_daily_spi_rules", new[] { "importer_code", "goods_description", "date_from", "date_to" }, unique: true);
        }
    }
}
