// Generated Time: 05/18/2020 19:37:55
// Generated By: AIKravchenko

using FilingPortal.Parts.Common.DataLayer.Base;

namespace FilingPortal.DataLayer.Migrations
{
    public partial class cbdev_3156_update_rail_product_description_rule : FpMigration
    {
        public override void Up()
        {
            DropIndex("dbo.imp_rail_rule_product", "Idx__description1");
            AddColumn("dbo.imp_rail_rule_product", "importer", c => c.String(maxLength: 128, unicode: false));
            AddColumn("dbo.imp_rail_rule_product", "supplier", c => c.String(maxLength: 128, unicode: false));
            AddColumn("dbo.imp_rail_rule_product", "port", c => c.String(maxLength: 4, unicode: false));
            CreateIndex("dbo.imp_rail_rule_product", new[] { "description1", "importer", "supplier", "port" }, unique: true, name: "Idx__description_importer_supplier_port");
            DropColumn("dbo.imp_rail_rule_product", "description");

            ExecuteSqlFileUp();
        }

        public override void Down()
        {
            AddColumn("dbo.imp_rail_rule_product", "description", c => c.String(maxLength: 128, unicode: false));
            DropIndex("dbo.imp_rail_rule_product", "Idx__description_importer_supplier_port");
            DropColumn("dbo.imp_rail_rule_product", "port");
            DropColumn("dbo.imp_rail_rule_product", "supplier");
            DropColumn("dbo.imp_rail_rule_product", "importer");
            CreateIndex("dbo.imp_rail_rule_product", "description1", unique: true, name: "Idx__description1");

            ExecuteSqlFileDown();
        }
    }
}
