// Generated Time: 09/28/2020 15:26:38
// Generated By: iapetrov

using FilingPortal.Parts.Common.DataLayer.Base;

namespace FilingPortal.DataLayer.Migrations
{

    public partial class cbdev_3338_change_get_audit_proc : FpMigration
    {
        public override void Up()
        {
            AddColumn("dbo.imp_rail_audit_daily_rules", "customs_attrib4", c => c.String(maxLength: 50, unicode: false));
            AddColumn("dbo.imp_rail_audit_daily_rules", "transactions_related", c => c.String(maxLength: 1, unicode: false));
            AddColumn("dbo.imp_rail_audit_daily", "customs_attrib4", c => c.String(maxLength: 50, unicode: false));

            ExecuteSqlFileUp();
        }

        public override void Down()
        {
            DropColumn("dbo.imp_rail_audit_daily", "customs_attrib4");
            DropColumn("dbo.imp_rail_audit_daily_rules", "transactions_related");
            DropColumn("dbo.imp_rail_audit_daily_rules", "customs_attrib4");

            ExecuteSqlFileDown();
        }
    }
}
