// Generated Time: 04/14/2021 14:21:55
// Generated By: ageorg

namespace FilingPortal.DataLayer.Migrations
{
    using FilingPortal.Parts.Common.DataLayer.Base;
    
    public partial class csfp_62_service_container_codes_transportmode : FpMigration
    {
        public override void Up()
        {
        }
        
        public override void Down()
        {
        }
    }
}
